- README.md
- afu_gewschutz_export_ai/export/build.gradle
afu_gewschutz_export_ai now works with an init script (updated README accordingly), uses relative paths for the SQL scripts and specifies the default task.
> Changes in afu_gewschutz_export_ai

- arp_aggloprogramme_pub/build.gradle
- arp_aggloprogramme_pub/gretl-job.groovy
Erstes Beispiel, wie die DB Connections mit Umgebungsvariablen und Variablen konfiguriert werden können. Damit das funktioniert, müssen in OpenShift bei der jenkins deployment configuration Umgebungsvariablen gesetzt werden. Weiter müssen gegenwärtig noch in Jenkins Credentials erfasst werden.
> Enable use of environment variables for DB connections

- agi_leitungskataster_pub/agi_leitungskataster_pub_lk_verfuegbarkeit.sql
Neu wird das inverse kopiert: nicht die Geometrien von Gemeinden, wo keine LK verfügbar ist, sondern wo Daten vorhanden sind). Zwischenlösung bis man pro Medium eine Tabelle hat.
> change lk verfuegbarkeit query

- agi_mopublic_pub/job.properties
- agi_wmts_hetzner_seeder/job.properties
Der DB-Import-Teil des AV-Import NG ist um ca. 02:30 Uhr Lokalzeit fertig. _agi_mopublic_pub_ soll also um 02:45 Lokalzeit starten, also um _01:45 UTC_.
Während der Sommerzeit bedeutet 01:45 UTC allerdings 03:45 Lokalzeit. D.h. zwischen Ende AV-Import und Start _agi_mopublic_pub_ liegt eine Stunde "brach", die wir in Kauf nehmen müssen.
_agi_mopublic_pub_ dauert ca. 7 Minuten. agi_wmts_hetzner_seeder soll deshalb um _02:00 UTC_ starten. Es dauert ca. 7h30min und ist also um ca. 9:30 UTC fertig, das ist während der Sommerzeit 11:30 Uhr Lokalzeit.
Gut möglich, dass nach der Ablösung der AV-Imports der AV-Import früher gestartet wird/werden kann. Dann könnten auch diese beiden Jobs füher gestartet werden.
In Jenkins gibt es übrigens auch das Feature "Starte Build, nachdem andere Projekte …
> Set specific trigger times

- agi_grundbuchplan_pub/job.properties
_agi_grundbuchplan_pub_ soll (praktisch) gleichzeitig mit _agi_mopublic_pub_ gestartet werden; dadurch sollten diese beiden Jobs vor 2:00 Uhr abgeschlossen sein. Zu diesem Zeitpunkt startet nämlich _agi_wmts_hetzner_seeder_, der die von diesen beiden Jobs importierten Daten benötigt.
> Set specific trigger time

- alw_gelan_pub/alw_gelan_pub_bienenstandorte.sql
- alw_gelan_pub/alw_gelan_pub_feuerbrand_schutzobjekte.sql
- alw_gelan_pub/alw_gelan_pub_feuerbrand_schutzperimeter.sql
- alw_gelan_pub/build.gradle
Dies funktioniert so: In den GELAN-Tabellen sind seit einiger Zeit jeweils mehrere Datenstände enthalten, identifizierbar durch das Attribut _jahr_. Es soll jeweils aber nur der Stand eines bestimmten Jahres publiziert werden. Ab welchem Zeitpunkt welcher Stand publiziert werden soll, ist aber nicht ganz fix. Es gibt Datensätze, bei denen irgendwann im Frühling der neue Stand publiziert werden soll, und solche, bei denen das irgendwann im Herbst der Fall ist.
Mit dem SQL-Parameter `publikationsjahr_wechsel_fruehling` im `build.gradle` kann nun eingestellt werden, welchen Jahresstand die Daten, die jeweils im Frühling umgestellt werden, abbilden sollen.
Mit dem SQL-Parameter `publikationsjahr_wechsel_herbst` kann eingestellt werden, welchen Jahresstand die Daten, die jeweils im Herbst …
> [alw_gelan_pub] 2 Parameter für Publikationsjahr hinzugefügt

- agi_plz_ortschaften_pub/gretl-job.groovy
Damit der GRETL-Job auch Zugriff auf die Edit-DB hat, was demnächst notwendig sein wird.
> [agi_plz_ortschaften_pub] Add Edit DB parameters

- agi_check_ili_export/build.gradle
Infolge Fehler in den Daten das Model SO_Agglomerationsprogramme_20170512 deaktiviert. Wird wieder aktiviert sobald die Daten bereinigt sind.
> [agi_check_ili_export] Model Aggloprogramme deaktiviert

- arp_zonenplan_pub/arp_zonenplan_pub_digitalisierter_zonenplan.sql
(SELECT DISTINCT t_datasetname::integer FROM arp_npl.nutzungsplanung_grundnutzung) ersetzt durch (2405,2408,2457,2473,2474,2476,2498,2501,2502,2580,2613,2614,2615)
=> Schema arp_npl gibt es auf Sogis DB nicht mehr!
> [arp_zonenplan_pub] Select auf Schema arp_npl geändert

- afu_isboden_pub/build.gradle
Erst mergen vor nächstem Rollout (20190917). Siehe auch Ticket https://geoweb.rootso.org/redmine/issues/3707
> [afu_isboden_pub] Erweiterung build.gradl für Indexierung Solr

- arp_npl_pub/transform_arp_npl_pub_erschliessung_flaechenobjekt_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_erschliessung_linienobjekt_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_grundnutzung_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_flaeche_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_linie_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_punkt_json_dokumente.sql
Die rekursive CTE verursachte immer noch Probleme bei Selbstreferenzen, d.h. Dokument A zeigt auf Dokument A. Sollte jetzt gelöst sein. Es bleibt eine kleine Unsicherheit, da die Query langsam einen Stand erreicht hat, wo ich nicht mehr alles verstehe... Auch nicht toll. 
Ein Refactoring der gesamten Query wäre sicher nicht falsch.
Was (noch) nicht abgefangen wird, sind indirekte Selbstreferenzen: Dokument A zeigt auf Dokument B. Dokument B zeigt auf Dokument A. Ob man das in einer Query unterbringt, weiss ich nicht. Auch weil man sich ja für eine Referenz entscheiden müsste.
> [arp_npl_pub] fix recursive cte (again)

- arp_richtplan_pub/arp_richtplan_pub_richtplankarte_grundnutzung_sogis.sql
[arp_richtplan_pub] gem_bfs NOT IN  erweitert um 2456
> [arp_richtplan_pub] gem_bfs NOT IN  erweitert

- Jenkinsfile
Instead of passing these from master to agent
Mit dieser Lösung werden neu die Ressourcen-Parameter wie DB_URI_PUB, AI_SERVER etc. nicht mehr auf dem Jenkins Master als Umgebungsvariablen gesetzt und im Jenkinsfile einzeln dem Jenkins Agent (Slave) übergeben, sondern sie werden in einer Config Map (Name _gretl-resources_) vorgehalten und deren Einträge als Umgebungsvariablen direkt in den Jenkins Agent gemountet. Siehe https://github.com/sogis/gretl/blob/86bb40e23bdc3ea79b4ec09896eeb3f4c80725b9/openshift/templates/gretl-pod-template-configmap.yaml#L54. Die Namen der Umgebungsvariablen starten jeweils mit dem Präfix `ORG_GRADLE_PROJECT_`; dadurch sind sie direkt in Gradle als Variablen nutzbar, jeweils mit dem Namen der Umgebungsvariable ohne Präfix.
Auch für die Credentials wird hiermit …
> Configure agent from OpenShift config map and secret

- Jenkinsfile
- README.md
- gretl_job_generator.groovy
Dies erlaubt es, durch Hinzufügen der Property `nodeLabel=gretl-ili2pg4` zur Datei `job.properties` den Job auf einem Jenkins Agent mit dem Label `gretl-ili2pg4` auszuführen. Wenn man das Property weglässt, wird er standardmässig auf einem Jenkins Agent mit dem Label `gretl` ausgeführt.
Diese Variante ist suboptimal, weil sie beim manuellen Start des Jobs den Benutzern einen Parameter anzeigt, was sie möglicherweise verunsichert. Zudem (aber irgendewie auch zur Vereinfachung) haben sie keine Möglichkeit, den Parameter umzustellen (es steht nur eine Option zur Auswahl). Deshalb **noch warten mit mergen dieses Pull Requests**. Vielleicht finde ich ja noch heraus, wie ich das über eine Umgebungsvariable statt über einen Parameter lösen kann.
> Add nodeLabel property

- arp_npl_import/README.md
Beim NPL-Import muss man wegen eines Bugs in ili2pg-v3 einen Umweg über ili2gpkg machen. Der Bug wurde zwischenzeitlich gefixed: [[https://github.com/claeis/ili2db/issues/299]]. Der Fix sollte - soweit ich das anhand der Daten nachvollziehen kann - ab Version 4.3.1 gemacht sein. Damit kann der Import-Prozess vereinfacht werden.
> [arp_npl_import] Readme angepasst

- agi_grundbuchplan_pub/job.properties
- agi_mopublic_pub/job.properties
Nun bezieht _agi_mopublic_pub_ die Daten aus der Edit-DB. Dort ist der AV-Import um ca. 23:20 Lokalzeit fertig. Also kann _agi_mopublic_pub_ neu früher starten als bisher. Es könnte noch früher als 0:15, weil Jenkins in UTC funktioniert, aber das müsste ich nochmal genauer überdenken. Der Job muss auch früher starten, weil er seit der Umstellung auf segmentierte Kreisbogen ca. 1:10 dauert und sonst erst nach dem Seeder fertig ist. (Der Seeder muss evtl. zusätzlich noch später starten, weil dieser wieder in Lokalzeit funktioniert.)
Und _agi_grundbuchplan_pub_ soll starten, nachdem _agi_mopublic_pub_ fertig ist, weil es irgendwo auf agi_mopublic_pub.mopublic_gemeindegrenze zugreift, insbesondere auch um das Lieferdatum zu ermitteln: …
> Start agi_mopublic_pub earlier

- afu_erdwaermesonden_pub/job.properties
triggers.cron temporär aus job.properties entfernt
> [afu_erdwaermesonden_pub] triggers.cron entfernt

- afu_erdwaermesonden_weitere_pub/job.properties
triggers.cron temporär aus job.properties entfernt
> [afu_erdwaermesonden_weitere_pub] triggers.cron entfernt

- avt_ausnahmetransportrouten_export_ai/Jenkinsfile
- avt_ausnahmetransportrouten_export_ai/build.gradle
- avt_ausnahmetransportrouten_export_ai/job.properties
- start-gretl.sh
Das hochgeladene File hat nun bereits die Endung xtf. Dadurch konnte der Job vereinfacht werden. Neu wird auch das Zip im java.io.tmpdir erzeugt.
> [avt_ausnahmetransportrouten_export_ai] Uploaded file now always has xtf extension

- awjf_biotopbaeume_pub/job.properties
Job auf Manuell umgestellt da dass Schema awjf_forsterviere von der sogis-DB auf die edit-DB gezügelt wurde.
Joins funktionieren aus diesem Grund nicht mehr:
```
FROM
awjf_biotopbaeume.biotopbaeume_biotopbaum biotopbaum
LEFT JOIN awjf_forstreviere.forstreviere_forstreviergeometrie AS forstgeometrie
ON
forstgeometrie.geometrie && biotopbaum.geometrie
AND
ST_Contains(forstgeometrie.geometrie, biotopbaum.geometrie)
LEFT JOIN awjf_forstreviere.forstreviere_forstrevier AS forstrevier
ON
forstgeometrie.forstrevier = forstrevier.t_id
LEFT JOIN awjf_forstreviere.forstreviere_forstkreis AS forstkreis
ON
forstgeometrie.forstkreis = forstkreis.t_id
```
> [awjf_biotopbaeume_pub] Job deaktiviert

- Jenkinsfile
Damit das Jenkinsfile ähnlich ist zu demjenigen in https://github.com/sogis/oereb-gretljobs/, wird es von "scripted pipeline" auf "declarative pipeline" umgestellt.
> Jenkinsfile umstellen auf declarative pipeline

- README.md
- development_dbs/setup.sql
- docker-compose.yml
* Pfad für Bind Mount relativ zum Compose File angeben (statt mit ${PWD})
* Named Volumes verwenden, damit die Daten auch nach einem docker-compose down erhalten bleiben
* Eindeutige Hostnamen verwenden
* Extension "pgaudit" nicht installieren, weil sie zu "fehlleitenden" Fehlermeldungen geführt hat
> Verbesserungen in docker-compose.yml

- README.md
- gretl_job_generator.groovy
Applied the following changes in order to keep `gretl_job_generator.groovy` in sync with https://github.com/sogis/oereb-gretljobs/blob/master/gretl_job_generator.groovy:
* Properties file may be UTF-8 encoded now
* `logRotator.numToKeep` also accepts `unlimited`
> Updates to gretl_job_generator.groovy

- Jenkinsfile
- README.md
- afu_abbaustellen_pub/Jenkinsfile
- afu_gefahrenkartierung_pub_export_ai/gradle.properties
- afu_nabodat_import/Jenkinsfile
- agi_check_ili_export/gradle.properties
- alw_fruchtfolgeflaechen/Jenkinsfile
- alw_fruchtfolgeflaechen_export_ai/gradle.properties
- arp_npl_import/Jenkinsfile
- avt_ausnahmetransportrouten_export_ai/Jenkinsfile
- avt_groblaermkataster_pub/Jenkinsfile
- avt_kantonsstrassen_pub/Jenkinsfile
- awjf_biotopbaeume_import/Jenkinsfile
- awjf_gesuchsteller/Jenkinsfile
Ich habe mich wieder mal mit RAM- und Heap-Limits auseinandergesetzt, weil ein Job von Martin mehr RAM benötigte. Und auch der Job _arp_npl_export_ai_, der ja nicht mehr durchläuft, hat mich für folgende Lösung inspiriert:
Das Argument `-Xmx...` für die JVM soll (innerhalb des Pod-Limits von gegenwärtig 3.5GB) neu durch die Job-Entwickler gesetzt werden können, indem sie eine Datei _gradle.properties_ im Job-Verzeichnis platzieren, in der z.B. steht: `org.gradle.jvmargs=-Xmx3g`. Damit das greift, muss nun aus allen Jenkinsfiles die Kommandozeilen-Option `-Dorg.gradle.jvmargs=-Xmx2G` entfernt werden. Denn diese Option übersteuert das, was man in _gradle.properties_ definiert. Deshalb hat z.B. der Job _arp_npl_export_ai_ nur 1864192 KB zur Verfügung, obwohl in _gradle.properties_ `-Xmx=3g` …
> Max. Heap Space in gradle.properties setzen

- avt_kunstbauten_pub/kunstbaute.sql
Infolge Probleme im Web GIS Client (Text wird im WGC als Datum interpretiert) muss der Platzhalte '-' mit einem '/' ersetzt werden bis sourcepole den Fehler behoben hat,
> [avt_kunstbauten_pub] Formatierung bezugspunkt angepasst

- Jenkinsfile
- README.md
- afu_abbaustellen_pub/Jenkinsfile
- afu_nabodat_import/Jenkinsfile
- afu_oekomorphologie_import/Jenkinsfile
- agi_dm01avso24/README.md
- alw_fruchtfolgeflaechen/Jenkinsfile
- arp_npl_import/Jenkinsfile
- arp_npl_pub/README.md
- avt_ausnahmetransportrouten_export_ai/Jenkinsfile
- avt_groblaermkataster_pub/Jenkinsfile
- avt_kantonsstrassen_pub/Jenkinsfile
- awjf_biotopbaeume_import/Jenkinsfile
- awjf_gesuchsteller/Jenkinsfile
- start-gretl.sh
This PR needs to be merged after merging and applying https://github.com/sogis/gretl/pull/60
Jobs tested in CRC, as far as possible:
Tested in test environment:
To do after the merge:
> Update Jenkinsfile for new Jenkins agent

- arp_npl_pub/arp_npl_pub_bfs_zuordnung.sql
- arp_npl_pub/arp_npl_pub_datenbereinigung.sql
- arp_npl_pub/auswertung_zonen_per_gemeinde.sql
- arp_npl_pub/build.gradle
- arp_npl_pub/transform_arp_npl_pub_erschliessung_beschriftung.sql
- arp_npl_pub/transform_arp_npl_pub_erschliessung_flaechenobjekt_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_erschliessung_linienobjekt_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_erschliessung_punktobjekt_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_beschriftung.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_grundnutzung_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_flaeche_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_linie_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_punkt_json_dokumente.sql
- arp_npl_pub/transform_arp_npl_pub_verfahrenstand_vs_perimeter_beschriftung.sql
- arp_npl_pub/transform_arp_npl_pub_verfahrenstand_vs_perimeter_verfahrenstand.sql
- arp_npl_pub/uebertrag_alte_sogisdaten_zonenplan_grundnutzung.sql
Die neue Attribut-Spalte "t_datasetname" enthält nun die ursprüngliche "BFS-Nr" aus der xtf-Datei, die Spalte "bfs_nr" wird durch Postgis-Overlay-Funktionen aus dem AV-Gemeindegrenzendatensatz bestimmt.
> [arp_npl_pub] fix dataset

- arp_nutzungsplanung_import/Jenkinsfile
- arp_nutzungsplanung_import/build.gradle
Dies ist ein Vorschlag für andere Task-Namen, weil ich die bestehenden nicht immer leicht zu verstehen fand.
Zudem wäre neu der Task `transferData` ergänzt durch ein `finalizedBy deleteData_import` (statt dass `deleteData_import`von `transferData`abhängt), was den Vorteil hat, dass man im ersten Schritt des Jenkinsfiles `transferData` statt `deleteData_import` aufrufen kann; dadurch wird der Ablauf aus meiner Sicht besser verständlich.
> [arp_nutzungsplanung_import] Umbenennung Tasks

- arp_nutzungsplanung_delete_dataset/Jenkinsfile
- arp_nutzungsplanung_delete_dataset/README.md
- arp_nutzungsplanung_delete_dataset/build.gradle
- arp_nutzungsplanung_delete_dataset/job.properties
- arp_nutzungsplanung_import/Jenkinsfile
- arp_nutzungsplanung_import/README.md
- arp_nutzungsplanung_import/build.gradle
- arp_nutzungsplanung_import/delete_arp_nutzungsplanung_transfer.sql
- arp_nutzungsplanung_import/insert_arp_nutzungsplanung_transfer.sql
- arp_nutzungsplanung_pub/Jenkinsfile
- arp_nutzungsplanung_pub/README.md
- arp_nutzungsplanung_pub/build.gradle
- arp_nutzungsplanung_pub/delete_arp_nutzungsplanung_transfer_pub.sql
- arp_nutzungsplanung_pub/insert_arp_nutzungsplanung_transfer_pub.sql
- arp_nutzungsplanung_pub/job.properties
Das Jenkinsfile ist nun, so dass man gefragt wird, ob man fortfahren oder nochmals exportieren möchte, siehe Jenkinsfile Zeile 40.
Bitte beachte auch noch die paar Kommentare unten.
Zudem habe ich noch einen Vorschlag zur Umbenennung der Task-Namen, weil ich sie nicht so verständlich fand. Dieser Vorschlag ist im Pull Request #1057. Falls du damit einverstanden bist, kannst du ihn mergen. (Er wird in diesen Branch hier, arp_nutzungsplanung_nachfuehrung gemergt.) Oder ich mache es für dich.
> arp_nutzungsplanung_nachfuehrung

- Jenkinsfile
Retry the _git_ **and** the _gretl_ step instead of just the _git_ step. Reason: The _gretl_ step sometimes fails because of e.g. `java.net.UnknownHostException: models.geo.admin.ch`. In these cases it is worth retrying the _gretl_step.
We don't modify the "special" Jenkinsfiles, because all of them are used for jobs that are started manually only. So they just must be started again by the user.
See https://sogis.openproject.com/projects/gretl/work_packages/1081
> Retry whole stage

- arp_nutzungsplanung_kanton_pub/job.properties
- gretl_job_generator.groovy
- jenkinsfile_docs.md
Aufräumarbeiten nach der Umbenennung der Property von `stringParam` zu `stringParams` und damit Ermöglichung der Übergabe von mehreren String-Parametern.
> Fixup: stringParams

- agi_av_import_export/build.gradle
- agi_check_ili_export/build.gradle
- agi_mopublic_pub_export/build.gradle
Requires that the `ili2dbModeldir` and the `ilivalidatorModeldir` properties are set. See https://github.com/sogis/gretl/pull/67 for an example.
However, these properties are not mandatory. If they are not set the ili2db and ilivalidator defaults are used.
> Add modeldir option

- agi_av_import_export/build.gradle
In diesem besonderen Fall (Task-Typ _Av2ch_) setzen wir `modeldir` fix auf einen URL-String. Denn mir scheint, dass dieser Task-Typ den Ausdruck `%ITF_DIR;https://geo.so.ch/models/;%JAR_DIR/ilimodels` nicht versteht. Im Log wird nämlich gemeldet:
```
Folder /tmp/workspace/agi_av_import_export/agi_av_import_export/%ITF_DIR doesn't exist; ignored
[...]
Folder /tmp/workspace/agi_av_import_export/agi_av_import_export/%JAR_DIR/ilimodels doesn't exist; ignored
```
Aber dieser Task-Typ berücksichtigt ebenfalls die _ParentSites_, weshalb der Eintrag `https://geo.so.ch/models/` ausreicht. Log-Auszug:
```
lookup model <DM01AVCH24LV95D> 1.0 in repository <%ITF_DIR/>
Folder /tmp/workspace/agi_av_import_export/agi_av_import_export/%ITF_DIR doesn't exist; ignored
lookup model <DM01AVCH24LV95D> 1.0 in …
```
> [agi_av_import_export] modeldir setzen

- Jenkinsfile
- README.md
- afu_abbaustellen_pub/Jenkinsfile
- afu_nabodat_import/Jenkinsfile
- afu_oekomorphologie_csvimport/Jenkinsfile
- agi_check_ili_export/Jenkinsfile
- alw_fruchtfolgeflaechen/Jenkinsfile
- arp_mjpnl_initialisierung/Jenkinsfile
- arp_npl_import/Jenkinsfile
- arp_nutzungsplanung_delete_dataset/Jenkinsfile
- arp_nutzungsplanung_import/Jenkinsfile
- arp_nutzungsplanung_import_ersterfassung/Jenkinsfile
- arp_nutzungsplanung_kanton_pub/Jenkinsfile
- arp_nutzungsplanung_pub/Jenkinsfile
- arp_nutzungsplanung_pub_easy_validation/Jenkinsfile
- avt_ausnahmetransportrouten_export_ai/Jenkinsfile
- avt_groblaermkataster_pub/Jenkinsfile
- avt_kantonsstrassen_pub/Jenkinsfile
- avt_oev_gueteklassen_import/Jenkinsfile
- awjf_biotopbaeume_import/Jenkinsfile
- awjf_gesuchsteller/Jenkinsfile
- gretl_job_generator.groovy
Reasons:
* _main_ is now the default for new repos on GitHub
* https://github.com/sogis/schema-jobs and https://github.com/sogis-oereb/oereb-gretljobs already use _main_ for their default branch; with this change, all GRETL job repos use the same name for their default branch
The developers will need to follow the instructions under https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes in order to update their local clone of the repo.
> Rename default branch to main

- agi_av_import_export/build.gradle
- agi_check_ili_export/build.gradle
- agi_mopublic_pub_export/build.gradle
Because in these cases the models are found in the DB anyways. (The ili2db default starts with `%ILI_FROM_DB`.)
> Don't set modeldir

- README.md
- agi_check_ili_export/job.properties
Frühestens dann mergen, wenn GRETL 2.2 in einer ausgereiften Version vorhanden ist.
Evtl. brauchen wir dies allerdings gar nicht. Aber es ist hier als Vorbereitung, falls nach der Umstellung auf GRETL 2.2 doch noch eine weitere GRETL-Version verfügbar sein sollte. Und es soll im Hinblick auf weitere Situationen, wo zwei GRETL-Versionen parallel betrieben werden müssen, hier im Repo bleiben.
Muss dann unter Umständen auch noch bei den ÖREB-GRETL-Jobs und den Schema-Jobs umgesetzt werden.
> Möglichkeit, den Job mit GRETL 2.2 auszuführen

- README.md
- agi_check_ili_export/build.gradle
- agi_mopublic_pub_export/build.gradle
- alw_fruchtfolgeflaechen_pub/build.gradle
_ili2gpkg_ (_ili2db_) ignoriert ihm unbekannte Platzhalter wie z.B. `%ITF_DIR`, das von `ilivalidator` benutzt wird. Deshalb können wir für _ili2gpkg_-Tasks ebenfalls das `ilivalidatorModeldir` verwenden und brauchen also keine separate Variable für _ili2db_-Tasks.
Genauer gesagt ist bei _ili2gpkgImport_ so:
Falls das Modell nicht vorgängig in die DB importiert worden ist (mit `--schemaimport`), kann man einfach `modeldir = ilivalidatorModeldir` verwenden. Dies ist bei uns wohl der häufigste Fall. Falls das Modell bereits importiert worden ist, also bereits im GeoPackage vorhanden ist, soll man die `modeldir`-Option nicht setzen, damit das Modell direkt in der GeoPackage-Datei gefunden wird und somit auch sicher die richtige Version verwendet wird.
> Use ilivalidatorModeldir instead of ili2dbModeldir in Ili2gpkg tasks

- README.md
- arp_agglomerationsprogramme_pub/job.properties
- gretl_job_generator.groovy
Bei der Erteilung von Berechtigungen auf einem Job können neu mehrere Benutzer oder Gruppen mit Komma getrennt aneinandergereiht werden. Z.B.
`authorization.permissions=gretl-users-barpa,gretl-users-bvtaa`
> Feature: Grant permission to multiple roles

- awjf_statische_waldgrenzen_export_ai/awjf_statische_waldgrenzen_mgdm.sql
Es wurde ein altes ÖREB-Annex-Schema verwendet, um herauszufinden, welche Gemeinden freigeschaltet sind. Ich habe zuerst auf das neue Schema umgebogen und anschliessen diese Prüfung komplett gelöscht, da alle Gemeinden freigeschaltet sind.
> Statische Waldgrenzen MGDM fix

- arp_nutzungsplanung_planregister_pub_alles/build.gradle
- arp_nutzungsplanung_planregister_pub_alles/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
- arp_nutzungsplanung_planregister_pub_alles/dummy.txt
- arp_nutzungsplanung_planregister_pub_alles/insert_arp_nutzungsplanung_planregister_pub_grundwasserschutz.sql
- arp_nutzungsplanung_planregister_pub_alles/insert_arp_nutzungsplanung_planregister_pub_kantonal.sql
- arp_nutzungsplanung_planregister_pub_alles/insert_arp_nutzungsplanung_planregister_pub_kommunal.sql
- arp_nutzungsplanung_planregister_pub_alles/insert_arp_nutzungsplanung_planregister_pub_naturreservate.sql
- arp_nutzungsplanung_planregister_pub_alles/insert_arp_nutzungsplanung_planregister_pub_waldgrenze.sql
- arp_nutzungsplanung_planregister_pub_alles/insert_basket.sql
- arp_nutzungsplanung_planregister_pub_alles/insert_dataset.sql
- arp_nutzungsplanung_planregister_pub_alles/job.properties
für die Lieferung an Typos3. Wird gebraucht damit das Schema auf der pub einmal befüllt wird. Danach werden Dataset aktualisiert mit den gretljob z.B. arp_nutzungsplanung_pub.
> [arp_nutzungsplanung_planregister_pub_alles] neuer Job

- arp_mjpnl_migration/build.gradle
- arp_mjpnl_migration/delete_mjpnl_before_import.sql
- arp_mjpnl_migration/mjpnl_dummy_entries.sql
- arp_mjpnl_migration/mjpnl_leistung.sql
- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
- arp_mjpnl_migration/mjpnl_postprocessing_fill_t_basket.sql
- arp_mjpnl_migration/mjpnl_postprocessing_vereinbarung_uzl-region.sql
- arp_mjpnl_migration/mjpnl_vereinbarung.sql
Und nutze Dummy-Baskets (sowie basket UZL Region) für die Datenrequests aus der alten DB (Leistungen, Vereinbarungen).
Man könnte den korrekten Basket auch ermitteln anhand der t_ili_tid, wenn diese stabil ist...
> [arp_mjpnl_migration] Ermittle Baskets aus den t_ili2db_basket Tabelle 

- arp_nutzungsplanung_planregister_pub_alles/build.gradle
- arp_nutzungsplanung_planregister_pub_alles/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
nur doppelte Dokumente entfernen falls die Gemeinde und URL gleich ist. Senden an Typos3 angepasst.
> Arp planregister pub alles v4

- arp_nutzungsplanung_planregister_pub_alles/Jenkinsfile
- arp_nutzungsplanung_planregister_pub_alles/build.gradle
- arp_nutzungsplanung_planregister_pub_alles/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
task ziplanregister angepasst, SQL delete doppelte Einträge  mit "offiziellenr"  in der WHERE Bedingung  ergänzt , damit die doppelten Dokumente mit URL "nicht digital-verfügbar" nicht gelöscht werden.
> [arp_nutzungsplanung_planregister_pub_alles] 

- arp_mjpnl_migration/build.gradle
- arp_mjpnl_migration/delete_mjpnl_before_import.sql
- arp_mjpnl_migration/mjpnl_dummy_entries.sql
- arp_mjpnl_migration/mjpnl_leistung.sql
- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
- arp_mjpnl_migration/mjpnl_vereinbarung.sql
| stat.kurzbez | status_abrechnung|
|---|---|
| in Bearbeitung    | in_bearbeitung               | 
| freigegeben       | freigegeben                  | 
| ausbezahlt        | ausbezahlt                   | 
| ~fehlerhaft~      | *ist nicht vorhanden im Datensatz und wird ignoriert*      | 
| erledigt LW       | ausbezahlt                   | 
| Intern verrechnet | intern_verrechnet            | 
| ~Archiv~          | *ist nicht vorhanden im Datensatz und wird ignoriert*      | 
| ausbezahlt        | ausbezahlt                   | 
| übernommen ARP    | ausbezahlt                   | 
`TRUE` wenn:
- das datum_auszahlung von diesem Jahr (2023) ist (was bedeutet es ist bereits ausbezahlt)
- die Kurzbezeichnung der Art von einem von diesem ist: 'Korrektur Vorjahr', 'Unterhaltsbeitrag', …
> [arp_mjpnl_migration] `abrechnung_per_leistung` Abrechnung_Status und Einmalig

- agi_av_export_ai/build.gradle
Es wurde immer noch die S3-URLs verwendet.
> [agi_av_export_ai] fix wrong download url

- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
Berücksichtige die nicht-eindeutigen Status, wenn eine der Kind-Elemente "freigegeben" hat, ist der parent auch "freigegeben" und ansonsten sollten sich Status nicht unterscheiden (sind alle ausbezahlt oder alle intern_verrechnet).
- Hat eine Vereinbarung 3 Leistungen (eine `freigegeben` und zwei `ausbezahlt`), dann hat die `abrechnung_per_vereinbarung` den Status `freigegeben`.
- Hat eine Vereinbarung 3 Leistungen (alle `ausbezahlt`), dann hat die `abrechnung_per_vereinbarung` den Status `ausbezahlt`.
- Hat ein Bewirtschafter 3 Vereinbarungen (eine `freigegeben` und zwei `ausbezahlt`), dann hat die `abrechnung_per_bewirtschafter` den Status `freigegeben`.
Das heisst es werden auch die bereits ausbezahlten Leistungen berücksichtigt, auch wenn sie nicht "sichtbar" sind. Beispiel mit …
> [arp_mjpnl_migration] Zusammenzug der Leistungen

- arp_mjpnl_gelan_update/delete_gelandata_from_other_year.sql
- arp_mjpnl_initialisierung/delete_gelandata_from_other_year.sql
Wenn Monat kleiner 3 (März) soll das alte Jahr gelöscht werden anstelle von einer fehlerhaften kalkulation des sechzigsten Tages.
> [arp_mjpnl_initialisierung/gelan_update] Fix Jahr aus GELAN Daten löschen

- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_vereinbarung.sql
- Fix Status für Abrechnung per Bewirtschafter und per Vereinbarung bei Vor-Jahren (vorher waren alle auf freigegeben, sofern es 2023er mit freigegeben hatte)
- Berücksichtigen der Leistungen die "in_bearbeitung" sind in Abrechnung_per_Bewirtschafter und Abrechnung_per_Vereinbarung allerdings den Status auch demensprechen setzen. Es muss dann sichergestellt werden, dass es vor Zahlung kein "in_bearbeitung" gibt. Aufbauenda auf #1494
> [arp_mjpnl_migration] Fixes

- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_hecke.sql
- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_hostet.sql
- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_obl.sql
- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_weide_ln.sql
- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_weide_soeg.sql
- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_wiese.sql
- "Jäggi" in allen **Hecken**
- "Meier" in allen **OBL** und **Hostet** von 'Dorneck'
- "Gschwind-Holzherr" in allen **OBL** und **Hostet** ausser 'Dorneck'
- "Staub" in **Wiese**, **Weide_LN** und **Weide_Sög** von 'Solothurn', 'Lebern', 'Wasseramt'
- "Bruggisser" in **Wiese**, **Weide_LN** und **Weide_Sög** von 'Bucheggberg'
- "Jäggi" in **Wiese**, **Weide_LN** und **Weide_Sög** von 'Olten', 'Gösgen'
- "Solothurnmann" in **Wiese**, **Weide_LN** und **Weide_Sög** von 'Thal', 'Gäu'
- "Borer" in **Wiese**, **Weide_LN** und **Weide_Sög** von 'Dorneck'
- "Weber" in **Wiese**, **Weide_LN** und **Weide_Sög** von 'Thierstein'
**Nicht berücksichtigt wurden:**:
- Gschwind in Metzerlen (es ist  Meier anstelle drin) 
- Lüthy in Bettlach und Grenchen  (es ist  Staub anstelle drin)
> [arp_mjpnl_migration] Migriere Berater gemäss Bezirke

- arp_mjpnl_gelan_update/build.gradle
- arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschafter.sql
- arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschaftungseinheiten.sql
Neu setzen aller bewe_ids in `vereinbarung` aufgrund von intersections mit Bewirtschatungsflaechen.
Falls sie geändert hat, setzen des `bewe_id_ungeprueft`. 
Zusätzliches update der `gelan_pid_gelan` (bewirtschafter), falls nicht übersteuert.
> [arp_mjpnl_gelan_update] Update bewe_id mit Status "ungeprüft" und PID update

- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_migration/mjpnl_postprocessing_beurteilungen_hecke.sql
- arp_mjpnl_migration/mjpnl_vereinbarung.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_bewirtschafter.sql
- Verhindern, dass Flächen, die tote Links auf in existente Vereinbarungen enthalten, migriert werden.
- Kalkuliere nur abrechnung_per_bewirtschafter für das aktuelle Jahr (2023), denn für die anderen Jahren könnte es sein dass der Bewirtschafter nicht mehr der gleiche ist.
- Berücksichtige Lebhag und nehme nur dann die Meter für die Laufmeter.
> [arp_mjpnl_migration] Anpassungen nach Feedback (Rebound 8)

- arp_bauzonengrenzen_pub/create_bauzonengrenzen.sql
Es werden Gewässer und der Gewässerraum innerhalb der Bauzonen mitberücksichtigt. Insbesondere aus ästhetischen Gründen. In Absprache mit ARP. 
Es wird mit Toleranzen gearbeiten. Wenn 80% (momementan) des Umrisses innerhalb der Bauzone sind, wird es zur Bauzonen gerechnet. Gibt jedoch immer noch paar Edge Cases (Gewässer liegt z.B. zwischen Reserverzone und Bauzone).
> Verbesserte Bauzonengrenzen

- ada_archaeologie_pub/public/flaeche_insert.sql
Ohne GROUP BY gibt es doppelte Objekte (Fundstellen welche  Bauzonen und Reservezonen schneiden)
> [ada_archaeologie_pub] add GROUP BY

- README.md
- afu_gefahrenkartierung_pub_export_ai/Jenkinsfile
- afu_gefahrenkartierung_pub_export_ai/job.properties
Instead of providing and using a separate pod template with a bigger tmp volume, inherit from the _gretl_ pod template and add the volume mount using YAML. This allows to mount a sub path.
> Inherit from gretl pod template

- avt_kantonsstrassen_pub/build.gradle
Shape-Validator wieder aktiviert. Musste allerdings in 2 Tasks aufgeteilt werden, da das Validieren von mehreren Shapefiles nicht funktioniert (Siehe Doku des SHP-Validators)
> Avt kantonstrassen pub validator

- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
- arp_mjpnl_zahlungslauf/build.gradle
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_vereinbarung.sql
- arp_mjpnl_zahlungslauf/cleanup_mjpnl_abrechnung_per_leistung_orphans.sql
- arp_mjpnl_zahlungslauf/cleanup_mjpnl_abrechnung_per_leistung_status.sql
- arp_mjpnl_zahlungslauf/copy_mjpnl_abrechnung_per_leistung.sql
- Löschen von diesjährigen Leistungen ohne Vereinbarung (die wahrscheinlich manuell gelöscht wurden - normalerweise wird das nicht gemacht, sondern es wird eine Vereinbarung auf inaktiv geschalten). Dies ist wichtig, weil Leistungen nicht CASCADE verknüpft sind, damit die Daten bereinigt sind, falls man doch mal löscht.
- Setze für Vereinbarungen, die nicht aktiv sind oder nicht bewe-geprueft alle migrierten und einmaligen Leistungen, die `freigegeben` sind auf `in_bearbeitung`
- Setze für Vereinbarungen, die aktiv und bewe-geprueft sind alle migrierten Leistungen (nicht die einmaligen) die `in_bearbeitung` sind auf `freigegeben`.
- Berücksichtige in Zusammenfassungen (`abrechnung_per_vereinbarung` und `abrechnung_per_bewirtschafter`):
- nicht Leistungen die `in_bearbeitung` sind
- …
> [arp_mjpnl_zahlungslauf] Löschen von diesjährigen Leistungen ohne Vereinbarung

- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_vereinbarung.sql
... um die info über schnittzeitpunkt etc. zu kriegen.
In Abrechnung_per_Vereinbarung braucht es (für den Brief) einige Informationen wie zBs. der Schnittzeitpunkt. Diese werden aus der (evtl. migrierten und nicht besprochenen) Beurteilung gelesen. Dass diese nicht besprochen sein könnten, inkludiert gewissermassen "ungültige" Werte, die wir aber brauchen.
> [arp_mjpnl_zahlungslauf] Prüfe nicht ob die beurteilung besprochen ist

- arp_mjpnl_zahlungslauf/copy_mjpnl_abrechnung_per_leistung.sql
... der Vorjahresdaten, wenn die Vereinbarung kantonsintern ist
> [ARP_MJPNL_ZAHLUNGSLAUF] Setze Status 'intern_verrechnet' beim Kopieren 

- afu_infoflora/job.properties
As it seems that the infoflora server is often unreachable at earlier times
> [afu_infoflora] Run job later

- arp_mjpnl_zahlungslauf/build.gradle
Da ab 1.1.2024 noch nicht fürs 2024 berechnet werden soll. Statisch, bis wir eine Lösung haben.
> [arp_mjpnl_zahlungslauf] Setze 2023 auf Statisch für nächtliche Jobs

- README.md
- afu_isboden_csv_import/Jenkinsfile
- afu_isboden_csv_import/job.properties
- gretl_job_generator.groovy
There were changes to the file parameter functionality in the Jenkins Plugins, which require that we use the _file-parameters_ plugin for that. Which by the way solves file upload in a smarter and more secure way.
At the same time, implement this solution for the _afu_isboden_csv_import_ job. Other jobs will follow in a separate PR.
> File upload: Switch to stashedFile parameter

- arp_mjpnl_auszahlung/build.gradle
- arp_mjpnl_auszahlung/job.properties
- arp_mjpnl_auszahlung/update_mjpnl_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_auszahlung/update_mjpnl_abrechnung_per_leistung.sql
- arp_mjpnl_auszahlung/update_mjpnl_abrechnung_per_vereinbarung.sql
- arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschafter.sql
- arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschaftungseinheiten.sql
- arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_kulturflaechen.sql
- arp_mjpnl_zahlungslauf/build.gradle
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_hecke.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wbl_weide.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wbl_wiese.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_weide_ln.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_weide_soeg.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wiese.sql
- arp_mjpnl_zahlungslauf/job.properties
Im Januar muss auf das nächste Jahr umgeschaltet werden. Einige Regeln wurden definiert:
- Mutationen an den Vereinbarungen werden zwischen 1.12 und 15.1 nicht gemacht, um die Auszahlung nicht zu verfälschen.
- Bis zum 14.1 wird noch das Vorjahr genommen. Am 15.1 das aktuelle Jahr für die Kalkulation des Zahlungslaufs.
- Zusätzlich wird jetzt auch das Auszahlungsdatum gesetzt (auf den 15.12 des Vorjahres)
- Es wird einmal per Cron Job ausgeführt (am 15.1)
Ende Jahr bzw. Anfang Folgejahr, muss das Jahr abgeschlossen werden. Der Zeitplan sieht folgendermassen aus:
- 1. Dezember: GELAN Update führt nicht mehr zu Bewirtschafterwechsel
- 1. Dezember bis 14. Januar: Wird der Auszahlungsbrief generiert, es können noch anpassungen gemacht werden. Täglich wird die Zahlungslaufkalkulation für das …
> [arp_mjpnl_*] Jahreswechsel

- arp_richtplan_abbaustellen_pub/arp_richtplan_pub_abbaustellen.sql
- Anpassung sql arp_richtplan_pub_abbaustellen.sql
- Zusätzlicher Filter: richtplannummer IS NOT NULL (werden für arp_richtplan_pub_v2 nicht benötigt)
> [arp_richtplan] adjust sql

- arp_nutzungsplanung_kanton_pub/insert_arp_nutzungsplanung_planregister_pub_kantonal.sql
- arp_nutzungsplanung_pub/insert_arp_nutzungsplanung_planregister_pub_kommunal.sql
t_id ins Planregister nicht übernehmen . Bei arp_nutzungsplanung_planregister_pub_alles war es richtig.
> [arp_nutzungsplanung]

- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_alr_buntbrache.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_alr_saum.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_hecke.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_hostet.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_obl.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wbl_weide.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wbl_wiese.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_weide_ln.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_weide_soeg.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wiese.sql
- arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_vereinbarung.sql
- arp_mjpnl_zahlungslauf/cleanup_mjpnl_abrechnung_per_leistung_status.sql
- arp_mjpnl_zahlungslauf/copy_mjpnl_abrechnung_per_leistung.sql
- arp_mjpnl_zahlungslauf/delete_mjpnl_migrierte_leistungen.sql
Prüfe ist_nutzungsvereinbarung, wenn man die Leistungen kalkuliert. Nutzungsvereinbarungen werden analog inaktiven Vereinbarungen nicht behandelt
> [arp_mjpnl_zahlungslauf] Ignoriere nutzungsvereinbarungen

- arp_nutzungsplanung_kanton_pub/insert_arp_nutzungsplanung_transfer_pub.sql
- arp_nutzungsplanung_pub/insert_arp_nutzungsplanung_transfer_pub.sql
where Bedingung bei publiziertBis war nicht korrekt. Das führte zu doppelten Planungszonen in der Pub-DB
> [arp_nutzungsplanung_pub]

- arp_mjpnl_v2_gelan_update/mjpnl_update_vereinbarungen_gelan_kulturflaechen.sql
Offenbar kann ST_MaximumInscribedCircle bei gewissen Geometrien nicht gemacht werden, obwohl sie überschneiden und valide sind. Bei Area >1 geht es in diesem Fall und es ist allgemein ein Check der Sinn macht, denn vorher wurden viele minimale überschneidungen genommen.
> [arp_mjpnl_v2_gelan_update] Area check bei Überschneidung Vbg und Kultur

- agi_av_mocheckso/build.gradle
This way the CsvValidator will look for the model in the SO repo first
> [agi_av_mocheckso] Set default modeldir

- awjf_waldportal/job.properties
Gretljob läuft zurzeit infolge eines Geometriefehlers nicht durch.
> [awjf_waldportal] nächtliche Ausführung temporär deaktiviert

- arp_mjpnl_v2_auszahlung/update_mjpnl_abrechnung_per_bewirtschafter.sql
- arp_mjpnl_v2_auszahlung/update_mjpnl_abrechnung_per_leistung.sql
- arp_mjpnl_v2_auszahlung/update_mjpnl_abrechnung_per_vereinbarung.sql
wenn Zahlungslauf abgeschlossen ist
(nicht nur freigegeben)
> [arp_mjpnl_v2_auszahlung] intern_verrechnet soll auf ausbezahlt umschalten

- docker-compose.yml
Avoid permission issues by using an existing directory as source
> [docker-compose] Avoid permission issues

- agi_schema_dump/Jenkinsfile
- agi_schema_dump/build.gradle
- agi_schema_dump/create_dump.sh
- agi_schema_dump/job.properties
@schmandr Wie besprochen.
Bemerkungen / Fragen:
- Verwenden von ORG_GRADLE_PROJECT_dbUserEdit / dbPwdEdit auch für die Pub-Db sollte in Ordnung sein, oder?
- archiveArtifacts '/tmp/schema.dump' wird wahrscheinlich noch nicht funktionieren, da wohl kein volume Mount auf /tmp existiert und da  gemäss Jenkins Dok "archiveArtifacts" nur auf den Inhalt des "Workspace-Ordners" (und darunter) zugreifen kann - also wohl nicht auf /tmp
- geodb.rootso.org ist noch hardcodiert, da ich nicht weiss, ob eine entsprechende env existiert für die hosts 
- pg_dump sollte nicht nach dem Passwort "promten", da die env PGPASSWORD gesetzt ist - funktioniert beim lokalen ausprobieren.
Falls dies noch zu viele Fragezeichen sind: Vertragen und beispielsweise Sandra bitten, einen Dump des Edit-Schemas …
> Agi schema dump

- agi_av_kaso_abgleich_pub/agi_av_kaso_abgleich_import_differenzen_staging.sql
- agi_av_kaso_abgleich_pub/agi_av_kaso_abgleich_import_uebersicht_des_vergleichs_staging.sql
- agi_av_kaso_abgleich_pub/agi_av_kaso_abgleich_pub_differenzen.sql
- agi_av_kaso_abgleich_pub/agi_av_kaso_abgleich_pub_uebersicht_des_vergleichs.sql
- agi_av_kaso_abgleich_pub/build.gradle
- agi_av_kaso_abgleich_pub/delete_from_agi_av_kaso_abgleich_import.sql
**Hintergrund**:
Auftrag: https://sogis.openproject.com/projects/task/work_packages/2660
Das Edit Schema des Topics agi_av_kaso_abgleich wird auf Basis eines bestehenden Modells neu durch einen Schema Job angelegt (bisher manuell), siehe https://github.com/sogis/schema-jobs/commit/5a50af47b2d10e4d925aa0eadbd792eb53d8cfdd. Der alte Schema Name ist `agi_av_kaso_abgleich_import`, der neue, standardkonforme ist `agi_av_kaso_abgleich_v1`.
**Änderung**:
Dieser Pull Request betrifft den Daten-Job, der neu das Edit Schema `agi_av_kaso_abgleich_v1` referenziert (anstatt ...`_import`).
**Testbericht**:
Der Change wurde auf TEST und INT erfolgreich getestet (Schema-Job und Daten-Job fehlerfrei ausgeführt). Das neue Schema DDL unterscheidet sich einzig durch zusätzliche Constraints vom alten, und ein …
> [agi_av_kaso_abgleich] reference new edit schema

- afu_hydro_messstationen_pub/messstationen.sql
Es gibt auch Messstationen ausserhalb des Kantons. Diese dürfen bei der Publikation nicht zu einem Fehler führen.
> [afu_hydro_messstationen_pub]Coalesce bei Gemeindenamen

- agi_schema_dump/Jenkinsfile
- docker-compose.yml
And switch processing DB images to Alpine (postgis/postgis: 17-3.5-alpine) at the same time. This way maintenance of the sogis/postgis:16-3.4-bookworm image isn't needed anymore:
* https://github.com/sogis/docker-postgis/tree/main/16-3.4-bookworm
* https://hub.docker.com/r/sogis/postgis/tags?name=bookworm
> Upgrade to PostgreSQL 17

- alw_fruchtfolgeflaechen/Jenkinsfile
And switch to Alpine image postgis/postgis:17-3.5-alpine at the same time.
> [alw_fruchtfolgeflaechen] Upgrade processing DB to tag 17-3.5-alpine
