arp_npl_import/README.md
arp_npl_import/build.gradle
arp_npl_import/init.gradle
arp_npl_import/transform_arp_npl_pub_erschliessung_beschriftung.sql
arp_npl_import/transform_arp_npl_pub_erschliessung_flaechenobjekt.sql
arp_npl_import/transform_arp_npl_pub_erschliessung_linienobjekt.sql
arp_npl_import/transform_arp_npl_pub_erschliessung_punktobjekt.sql
arp_npl_import/transform_arp_npl_pub_nutzungsplanung_beschriftung.sql
arp_npl_import/transform_arp_npl_pub_nutzungsplanung_grundnutzung.sql
arp_npl_import/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_flaeche.sql
arp_npl_import/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_linie.sql
arp_npl_import/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_punkt.sql
arp_npl_import/transform_arp_npl_pub_transfermetadaten.sql
arp_npl_import/transform_arp_npl_pub_vs_perimeter_beschriftung.sql
arp_npl_import/transform_arp_npl_pub_vs_perimeter_verfahrensstand.sql

GRETL job for importing and transformation of Nutzungsplanung.

Nplso import

---

README.md

readme komplett auf deutsch

---

README.md
scripts/start-gretl.sh
scripts/test-gretl.sh

Update wrapper scripts: Docker Repository und Umgebungsvariablen für DB-Verbindungen

---

arp_aggloprogramme_pub/build.gradle
arp_aggloprogramme_pub/gretl-job.groovy

I updated the variable names so they are more readable.

Updated variable names

---

arp_aggloprogramme_pub/gretl-job.groovy

Instead of hard coded repo URL

Use GRETL_JOB_REPO_URL environment variable

---

avt_oeffentlicher_verkehr_pub/avt_oeffentlicher_verkehr_pub_haltestellen.sql

Attribute nr_tu und verksmittel: Code durch Text ersetzt

Code durch Text ersetzt

---

afu_gewisso_pub/afu_gewisso_pub_gewisso_line_merge.sql
afu_gewisso_pub/build.gradle

DDL first! see [https://geoweb.rootso.org/redmine/issues/3035](https://geoweb.rootso.org/redmine/issues/3035)

add additional sql file and adjust gradle

---

awjf_wald_pub/awjf_wald_pub_sw_funktion_ar.sql
awjf_wald_pub/awjf_wald_pub_waldge.sql

Offensichtlich ist hier das awjf_wald_pub/awjf_wald_pub_sw_funktion_ar.sql auch nochmal dabei. Müsste nicht sein, macht aber auch nichts.

Awjf wald pub 2

---

afu_vsb_pub/afu_vsb_pub_flaeche.sql

Bitte reviewen (jemand) und anschliessend mergen.

adding missing attributes

---

agi_av_gb_abgleich_pub/gretl-job.groovy
agi_av_kaso_abgleich_pub/gretl-job.groovy

Add variables for KASO and Capitastra DBs

---

arp_npl_import/README.md

Anleitung für Import und Datenumbau. Nur Doku, dh. Änderungen im README innerhalb des Job-Directories.

[arp_npl_import] Anleitung für Import von NPLSO-Operaten

---

arp_npl_import/README.md

Anleitung für Datenumbau in/für alte(r) Welt.

[arp_npl_import] doku fix

---

agi_av_gb_administrative_einteilungen_pub/transform_grundbuchkreise_grundbuchkreis.sql
agi_av_gb_administrative_einteilungen_pub/transform_nachfuehrngskrise_gemeinde.sql

change schema name in sql files

[agi_av_gb_admin_einteilungen] change schema name in sql files

---

arp_npl_pub/transform_arp_npl_pub_erschliessung_flaechenobjekt_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_erschliessung_linienobjekt_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_grundnutzung_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_flaeche_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_linie_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_punkt_json_dokumente.sql

Getestet mit geodb-t und geodb. Link kopiert und in Browser eingefügt. Funktioniert.

[arp_npl_pub] adjust url to pdf docs

---

afu_gewaesserschutz_pub/afu_gewaesserschutz_pub_aww_gsab.sql
afu_gewaesserschutz_pub/afu_gewaesserschutz_pub_aww_gszoar.sql
afu_gewschutz_export_ai/export/gsareal_insert.sql
afu_gewschutz_export_ai/export/gsbereich_insert.sql
afu_gewschutz_export_ai/export/gszone_insert.sql

"zone" ist ein non-reserved sql keyword. 
Ob es die ideale Lösung ist mit dem Quoting... Who knows.

[keywords] quote attr name 'zone'

---

README.md
afu_abbaustellen_pub/job.properties
afu_gewaesserschutz_pub/job.properties
arp_ivs_pub/job.properties
arp_npl_pub/job.properties
arp_wanderwege_pub/job.properties
awjf_wald_pub/job.properties

At the same time, switch to the new group names.

Set some more permissions

---

avt_gesamtverkehrsmodell2015_pub/avt_gesamtverkehrsmodell2015_pub_gvm_so_2015_oev.sql

Added streckentyp to gretl-job

added streckentyp to gesamtverkehrsmodell2015_oev_pub model

---

avt_gesamtverkehrsmodell2015_pub/avt_gesamtverkehrsmodell2015_pub_gvm_so_2015_oev.sql

bugfix gvm15_oev

---

afu_grundwasserbewirtschaftung_pub/afu_grundwasserbewirtschaftung_fassung_pub.sql
afu_grundwasserbewirtschaftung_pub/afu_grundwasserbewirtschaftung_grundwassereinbauten_pub.sql
afu_grundwasserbewirtschaftung_pub/afu_grundwasserbewirtschaftung_grundwasserwaermepumpen_entnahmeschacht_pub.sql
afu_grundwasserbewirtschaftung_pub/afu_grundwasserbewirtschaftung_quellen_pub.sql
afu_grundwasserbewirtschaftung_pub/afu_grundwasserbewirtschaftung_trinkwasserobjekte_pub.sql
afu_grundwasserbewirtschaftung_pub/build.gradle
afu_grundwasserbewirtschaftung_pub/gretl-job.groovy
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_fassung_pub.sql
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_grundwassereinbauten_pub.sql
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_grundwasserwaermepumpen_entnahmeschacht_pub.sql
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_quellen_pub.sql
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_trinkwasserobjekte_pub.sql
afu_wasserbewirtschaftung_pub/build.gradle
afu_wasserbewirtschaftung_pub/gretl-job.groovy

integration der wasserbewirtschaftungs-jobs in den master

Afu grundwasserbewirtschaftung pub

---

awjf_jagd_pub/awjf_jagd_pub_jagdbanngebiete.sql
awjf_jagd_pub/awjf_jagd_pub_jagdreviere.sql
awjf_jagd_pub/gretl-job.groovy
awjf_jagd_pub/job.properties

Awjf jagd pub 3308

---

README.md
scripts/start-gretl.sh

Add gretlShare variable

---

README.md
scripts/start-gretl.sh

Solves https://github.com/sogis/gretl/issues/97

Accept any Gradle options in start-gradle.sh

---

arp_npl_pub/transform_arp_npl_pub_erschliessung_flaechenobjekt_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_erschliessung_linienobjekt_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_grundnutzung_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_flaeche_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_linie_json_dokumente.sql
arp_npl_pub/transform_arp_npl_pub_nutzungsplanung_ueberlagernd_punkt_json_dokumente.sql

Abbruchkriterium für die rekursiven Queries hinzugefügt.

[arp_npl_pub] add abort criterion for recursive cte

---

README.md
scripts/start-gretl.sh

Add connection parameters for Aggregation Infrastructure (AI)

---

agi_check_ili_export/gretl-job.groovy

Sends an email if the job failed. To the default recipients configured in Jenkins config, and to the user that started the job (if started manually).

Send email if job failed

---

afu_gefahrenkartierung_pub_export_ai/gretl-job.groovy
afu_gefahrenkartierung_pub_export_ai/job.properties

Fix DB credential variables

---

avt_oevkov/insert_into_gtfs_auswertung.sql
awjf_biotopbaeume_pub/awjf_biotopbaeume_pub_biotopbaeume_biotopbaum.sql

Awjf biotopbaeume pub b3

---

awjf_seltene_baeume_pub/save_gretl-job.groovy

gretl-job.groovy temporaer geloescht damit Gretljob nicht taeglich mit Fehler laeuft

gretl-job.groovy temporaer umbenennt

---

afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_fassung_pub.sql
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_oberflaechenhydrometrie.sql
afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_quellen_pub.sql

Afu wasserbewirtschaftung pub

---

arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_geobasisdaten_laermempfindlichkeit_zonenflaeche.sql
arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_geobasisdaten_typ.sql
arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_geobasisdaten_typ_dokument.sql
arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_localiseduri.sql
arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_multilingualuri.sql
arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_rechtsvorschrften_dokument.sql
arp_npl_export_ai/arp_laermempfindlichkeit_mgdm_rechtsvorschrften_hinweisweiteredokumente.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_grundnutzung_zonenflaeche.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_linienbezogene_festlegung.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_objektbezogene_festlegung.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_typ.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_typ_dokument.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_typ_kt.sql
arp_npl_export_ai/arp_npl_mgdm_geobasisdaten_ueberlagernde_festlegung.sql
arp_npl_export_ai/arp_npl_mgdm_localiseduri.sql
arp_npl_export_ai/arp_npl_mgdm_multilingualuri.sql
arp_npl_export_ai/arp_npl_mgdm_rechtsvorschrften_dokument.sql
arp_npl_export_ai/arp_npl_mgdm_rechtsvorschrften_hinweisweiteredokumente.sql
arp_npl_export_ai/build.gradle
arp_npl_export_ai/gretl-job.groovy
arp_npl_export_ai/truncate_all_arp_laermempfindlichkeit_mgdm_tables.sql
arp_npl_export_ai/truncate_all_arp_npl_mgdm_tables.sql

Various bug fixes and improvements. I'm creating this pull request on behalf of @barpastu.

[ arp_npl_export_ai] Various bug fixes and improvements

---

avt_verkehrszaehlstellen_pub/job.properties

Bugfix autorisation to autorization

[avt_verkehrszaehlstellen_pub] bugfix

---

ada_adagisa_pub/build.gradle
afu_abbaustellen_pub/build.gradle
afu_altlasten_pub/build.gradle
afu_erdwaerme_pub/build.gradle
afu_gewisso_pub/build.gradle
afu_ingeso_pub/build.gradle
alw_gelan_pub/build.gradle
arp_naturreservate_pub/build.gradle
avt_kantonsstrassen_pub/build.gradle
avt_oeffentlicher_verkehr_pub/build.gradle
avt_verkehrszaehlstellen_pub/build.gradle
awjf_jagd_pub/build.gradle
awjf_wald_pub/build.gradle

Einbau des Aufrufes für den Indexupdater

Erweiterung build.gradl für Indexierung Solr

---

alw_infoflora/build.gradle

[alw_infoflora] Update build.gradle

---

afu_wasserbewirtschaftung_pub/build.gradle

Pullrequets erst mergen vor Rollout (02.10.209)

[afu_wasserbewirtschaftung_pub] add DataSets Indexupdate

---

arp_richtplan_pub/arp_richtplan_pub_richtplankarte_grundnutzung_sogis.sql
avt_oevkov/berechnung_kosten.sql
avt_oevkov/insert_into_gtfs_auswertung.sql

Arp richtplan pub

---

avt_oevkov/haltestellenbuffer_insert.sql

[avt_oevkov] Nur Buffer für Haltestellen mit Anrechung

Nur Buffer für Haltestellen mit Anrechung

---

arp_richtplan_pub/arp_richtplan_pub_richtplankarte_grundnutzung_sogis.sql

[arp_richtplan_pub] gem_bfs NOT IN erweitert

---

avt_groblaermkataster_pub/.gitignore
avt_groblaermkataster_pub/DEV.md
avt_groblaermkataster_pub/README.md
avt_groblaermkataster_pub/build.gradle
avt_groblaermkataster_pub/gretl-job.groovy
avt_groblaermkataster_pub/job.properties

GRETL-Job für den Import des Groblärmkatasters.

Avt groblaermkataster

---

afu_altlasten_pub/afu_altlasten_pub_belastete_standorte.sql

Revert "[afu_altlasten_pub] Texte angepasst gemaess OEREB"

---

arp_richtplan_pub/arp_richtplan_pub_richtplankarte_grundnutzung_sogis.sql

[apr_richtplan_pub] Erweiterung gem_bfs NOT IN

---

avt_oevkov/build.gradle

Avt oevkov b1

---

afu_geotope/afu_geotope_geotope_aufschluss.sql
afu_geotope/afu_geotope_geotope_aufschluss_dokument.sql
afu_geotope/afu_geotope_geotope_aufschluss_fachbereich.sql
afu_geotope/afu_geotope_geotope_dokument.sql
afu_geotope/afu_geotope_geotope_erratiker.sql
afu_geotope/afu_geotope_geotope_erratiker_dokument.sql
afu_geotope/afu_geotope_geotope_erratiker_fachbereich.sql
afu_geotope/afu_geotope_geotope_fachbereich.sql
afu_geotope/afu_geotope_geotope_fundstelle_grabung.sql
afu_geotope/afu_geotope_geotope_fundstelle_grabung_dokument.sql
afu_geotope/afu_geotope_geotope_fundstelle_grabung_fachbereich.sql
afu_geotope/afu_geotope_geotope_hoehle.sql
afu_geotope/afu_geotope_geotope_hoehle_dokument.sql
afu_geotope/afu_geotope_geotope_hoehle_fachbereich.sql
afu_geotope/afu_geotope_geotope_landform_dokument.sql
afu_geotope/afu_geotope_geotope_landform_fachbereich.sql
afu_geotope/afu_geotope_geotope_landschaftsform.sql
afu_geotope/afu_geotope_geotope_quelle.sql
afu_geotope/afu_geotope_geotope_quelle_dokument.sql
afu_geotope/afu_geotope_geotope_quelle_fachbereich.sql
afu_geotope/afu_geotope_geotope_zustaendige_stelle.sql
afu_geotope/afu_geotope_lithostratigrphie_geologische_schicht.sql
afu_geotope/afu_geotope_lithostratigrphie_geologische_serie.sql
afu_geotope/afu_geotope_lithostratigrphie_geologische_stufe.sql
afu_geotope/afu_geotope_lithostratigrphie_geologisches_system.sql
afu_geotope/build.gradle

Erster merge dieses recht alten branches...

Afu geotope

---

alw_infoflora/build.gradle

Neu werden die files erst nach 2 Tagen gelöscht (wenn ein file 2 Tage alt ist). Gleichzeitig wird das erhaltene JSON nach Datum sortiert, so dass sichergestellt ist, dass der erste JSON-Eintrag das neuste file ist.

[alw_infoflora]Siehe Ticket 3772

---

afu_altlasten_pub/afu_altlasten_pub_belastete_standorte_altlast4web.sql

Change: Felder c_vflz_unterstand und c_vflz_bearbstand neu konkateniert.

Belastete standorte altlast4web

---

afu_erdwaermesonden_weitere_pub/build.gradle

delete dependsOn:'transferErdwaerme'

[afu_erdwaermesonden_weitere_pub] delete dependsOn

---

arp_npl_import/README.md

arp_zoneneplan_pub aus Readme gelöscht

[arp_npl_pub_import] change README

---

amb_zivilschutz_adressen_export/build.gradle
amb_zivilschutz_adressen_export/job.properties

Which is now included in GRETL runtime image

[amb_zivilschutz_adressen_export] Use org.hidetake.ssh plugin 

---

afu_erdwaermesonden_pub/job.properties

triggers.cron=H H(1-3) * * * hinzugefügt

[afu_erdwaermesonden_pub] erweiterung job.properties

---

afu_erdwaermesonden_weitere_pub/job.properties

triggers.cron=H H(1-3) * * * hinzugefügt

[afu_erdwaermesonden_weitere_pub] erweiterung job.properties

---

afu_vsb_pub/afu_vsb_pub_pruefperimeter.sql

https://geoweb.rootso.org/redmine/attachments/download/1687

[afu_vsb_pub_pruefperimeter] <br> entfernt

---

awjf_waldpflege_kontrolle/awjf_waldpflege_kontrolle.sql
awjf_waldpflege_kontrolle/build.gradle
awjf_waldpflege_kontrolle/delete_from_awjf_waldpflege_erfassung.sql
awjf_waldpflege_kontrolle/job.properties
awjf_waldpflege_kontrolle_pub/awjf_waldpflege_kontrolle_pub.sql
awjf_waldpflege_kontrolle_pub/build.gradle
awjf_waldpflege_kontrolle_pub/job.properties

Initial version

---

awjf_waldpflege_kontrolle/build.gradle

falsche DB

---

demo_file_upload/Jenkinsfile
demo_file_upload/build.gradle

Demo Job showing how the file upload workaround works

[demo_file_upload] Add file upload demo job

---

demo_file_upload/Jenkinsfile

and stash file from build directory

[demo_file_upload] Upload file to build directory

---

awjf_waldpflege_kontrolle_pub/build.gradle

[awjf_waldpflege_kontrolle_pub]: Daten löschen auf true gesetzt

Daten löschen auf true gesetzt

---

alw_zonengrenzen_import_pub/build.gradle

Initial import

---

agi_mopublic_pub/agi_mopublic_pub_mopublic_bodenbedeckung.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_bodenbedeckung_proj.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_einzelobjekt_flaeche.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_einzelobjekt_linie.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_einzelobjekt_punkt.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_fixpunkt.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_flurname.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_gebaeudeadresse.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_gelaendename.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_gemeindegrenze.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_gemeindegrenze_proj.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_grenzpunkt.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_grundstueck.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_grundstueck_proj.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_hoheitsgrenzpunkt.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_objektname_pos.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_ortsname.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_rohrleitung.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_strassenachse.sql
agi_mopublic_pub/agi_mopublic_pub_mopublic_strassenname_pos.sql

[agi_mobublic_pub] faster av mopublic sql scripts

---

alw_zonengrenzen_import/build.gradle
alw_zonengrenzen_import/delete_landwirtschaftliche_zonengrenzen_tables.sql
alw_zonengrenzen_import/job.properties

[alw_zonengrenzen_import] neu in Edit-DB

Zonengrenzen neu in Edit-DB

---

alw_zonengrenzen_import/alw_zonengrenzen_pub.sql
alw_zonengrenzen_import/build.gradle

alw_zonengrenzen_pub: Import neu in Edit-DB, anschliessend Transfer in Pub-DB

Alw zonengrenzen b6

---

awjf_waldpflege_kontrolle/Jenkinsfile
awjf_waldpflege_kontrolle/build.gradle
awjf_waldpflege_kontrolle/delete_from_awjf_gesuchsteller.sql

[awjf_waldpflege_kontrolle] Test mit Dateiupload

Test mit Dateiupload

---

awjf_waldpflege_kontrolle/build.gradle

[awjf_waldpflege_kontrolle] Test 2 mit Dateiupload

Test 2 mit Dateiupload

---

awjf_waldpflege_kontrolle/build.gradle

[awjf_waldpflege_kontrolle] Test 3 mit Dateiupload

Test 3 mit Dateiupload

---

agi_mopublic_pub/agi_mopublic_pub_mopublic_objektname_pos.sql

[agi_mopublic_pub] Bugfix: Select objects from last import only

---

avt_oevkov/insert_into_gesamtauswertung.sql

[avt_oevkov] Summe anzahl_abfahrten_linie fehlte in Auswertung

Summe anzahl_abfahrten_linie fehlte in Auswertung

---

avt_oevkov/insert_into_gesamtauswertung.sql

[avt_oevkov] das Problem mit UTF-8 detecting existiert anscheinend immer noch!

das Problem mit UTF-8 detectin existiert anscheinend immer noch!

---

avt_oevkov/insert_into_gtfs_auswertung.sql

[avt_oevkov] Anpassungen wegen geänderten Liniennamen

Anpassungen wegen geänderten Liniennamen

---

awjf_waldpflege_kontrolle_pub/build.gradle

[waldpflege_kontrolle] neu mit Upload des CSV in die Tabelle awjf_gesuchsteller.gesuchsteller.gesuchsteller

Schema nach _pub umbenannt

---

agi_avdpool_ng_sogis/agi_dm01avso24_gebaeudeadressen_strassenstueck.sql

[agi_avdpool_ng_sogis] Add missing attribute geometrie

---

awjf_waldpflege_kontrolle/build.gradle

[awjf_waldpflege] Modell ohne OID AS INTERLIS.UUIDOID wegen CsvValidator

Modell ohne OID AS INTERLIS.UUIDOID wegen CsvValidator

---

awjf_waldpflege_kontrolle/build.gradle

[awjf_waldkontrolle] Nicht mehr verwendete Variablen gelöscht

Nicht mehr verwendete Variablen gelöscht

---

awjf_biotopbaeume_import/job.properties

[awjf_biotopbaeume_import] Rechte für awjf setzen

Awjf biotopbaeume import

---

awjf_biotopbaeume_pub/awjf_biotopbaeume_pub_biotopbaeume_biotopbaum.sql
awjf_biotopbaeume_pub/build.gradle

[awjf_biotopbaeume_pub] Neu aus Schema awjf_foerderprogramm_biodiversitaet

Gretljob auf neues Schema awjf_foerderprogramm_biodiversitaet angepasst

---

agi_inventar_hoheitsgrenzen_pub/agi_inventar_hoheitsgrenzen_pub_kantonsgrenzstein.sql
agi_inventar_hoheitsgrenzen_pub/build.gradle
agi_inventar_hoheitsgrenzen_pub/job.properties

[agi_inventar_hoheitsgrenzen_pub] initial commit

[agi_inventar_hoheitsgrenzen_pub] initial commit

---

agi_inventar_hoheitsgrenzen_pub/build.gradle

[agi_inventar_hoheitsgrenzen_pub] Korrektur

[agi_inventar_hoheitsgrenzen_pub] Korrektur

---

agi_inventar_hoheitsgrenzen_pub/agi_inventar_hoheitsgrenzen_pub_kantonsgrenzstein.sql

[agi_inventar_hoheitsgrenzen_pub] nur schoener_stein = true

nur schoener_stein = true

---

agi_check_ili_export/datasets.groovy

[agi_check_ili_export] update richtplan model

Modellaenderung SO_ARP_Richtplan_20210210

---

arp_richtplan_pub/arp_richtplan_pub_detailkarten_ueberlagernde_Linie.sql
arp_richtplan_pub/arp_richtplan_pub_detailkarten_ueberlagernder_Punkt.sql
arp_richtplan_pub/arp_richtplan_pub_richtplankarte_ueberlagernde_flaeche.sql
arp_richtplan_pub/arp_richtplan_pub_richtplankarte_ueberlagernde_flaeche_sogis.sql
arp_richtplan_pub/arp_richtplan_pub_richtplankarte_ueberlagernde_linie.sql
arp_richtplan_pub/arp_richtplan_pub_richtplankarte_ueberlagernde_linie_sogis.sql
arp_richtplan_pub/arp_richtplan_pub_richtplankarte_ueberlagernder_punkt.sql
arp_richtplan_pub/build.gradle

[arp_richtplan_pub] Modelländerung, Zusammenfassung der Daten

Arp richtplan b1

---

agi_check_ili_export/datasets.groovy

[agi_check_ili_export] neuer Modellname Richtplan_Pub

[agi_check_ili_export] neuer Modellname

---

alw_strukturverbesserungen_pub/gemeinde.sql
alw_strukturverbesserungen_pub/genossenschaft.sql
alw_strukturverbesserungen_pub/massnahme.sql

Diverse Constraints wurden relaxt und Text-Attribute verlängert

ALW Strukturverbesserungen Pub

---

agi_mopublic_pub/agi_mopublic_pub_mopublic_gebaeudeadresse.sql

AND 
strassenname IS NOT NULL
AND
hausnummer IS NOT NULL

[agi_mopublic_pub] delete where-Bedingung

---

gretl_job_generator.groovy

Add view for generated jobs

---

start-gretl.sh

Weitere Information unter sogis/schema-jobs/pull/72.

Git bash compatibility

---

alw_fruchtfolgeflaechen/01_Datenimport/fruchtfolgeflaechen_alt.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/fff_100_ohne_schlechten_boden.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/fff_100_ohne_vereinbarungsflaechen.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/fff_50.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/fff_ohne_bodenkartierung.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/fff_zusammensetzen.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/maske_ohne_altlasten.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/maske_ohne_grundwasserschutz.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/maske_where_bodenkartierung.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/maske_where_not_bodenkartierung.sql
alw_fruchtfolgeflaechen/03_Uebersteuerung/fff_mit_uebersteuerung.sql
alw_fruchtfolgeflaechen/04_Finish/build.gradle
alw_fruchtfolgeflaechen/04_Finish/fff_clean.sql
alw_fruchtfolgeflaechen/04_Finish/fff_komplett.sql
alw_fruchtfolgeflaechen/04_Finish/fff_mit_gewaesserraum.sql
alw_fruchtfolgeflaechen/04_Finish/fff_to_edit_db_finish.sql
alw_fruchtfolgeflaechen/04_Finish/fff_to_edit_db_finish_old.sql

Viele kleinere Anpassungen / Korrekturen + grosse Geometriebereinigung am Ende

Fruchtfolgeflaechen v4

---

alw_fruchtfolgeflaechen/01_Datenimport/build_local.gradle
alw_fruchtfolgeflaechen/01_Datenimport/prepare_db.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/maske_ohne_grundwasserschutz.sql
alw_fruchtfolgeflaechen/02_Vorberechnung/maske_ohne_schadstoffbelastete_boeden.sql
alw_fruchtfolgeflaechen/03_Uebersteuerung/fff_mit_uebersteuerung.sql
alw_fruchtfolgeflaechen/03_Uebersteuerung/fff_to_edit_db.sql
alw_fruchtfolgeflaechen/04_Finish/fff_komplett.sql
alw_fruchtfolgeflaechen/04_Finish/fff_mit_gewaesserraum.sql

Alw fruchtfolgeflaechen v5

---

arp_auswertung_nutzungsplanung_pub/bauzonenstatistik_bebauungsstand_mit_zonen_ohne_lsgrenzen.sql
arp_auswertung_nutzungsplanung_pub/bauzonenstatistik_bebauungsstand_mit_zonen_und_lsgrenzen.sql
arp_auswertung_nutzungsplanung_pub/bauzonenstatistik_bebauungsstand_pro_gemeinde.sql
arp_auswertung_nutzungsplanung_pub/bauzonenstatistik_gines.sql
arp_auswertung_nutzungsplanung_pub/bauzonenstatistik_liegenschaft_nach_bebauungsstand.sql
arp_auswertung_nutzungsplanung_pub/build.gradle

Initialer Check-in Bauzonenstatistik

[arp_auswertung_nutzungsplanung_pub] Initial check-in

---

alw_fruchtfolgeflaechen/02_Vorberechnung/fff_50.sql
alw_fruchtfolgeflaechen/04_Finish/fff_statistik.sql

Neue Bodenparameter gemäss Exceltabelle von Jennifer Jauch
[FFF_isBoden.xlsx](https://github.com/sogis/gretljobs/files/8001673/FFF_isBoden.xlsx)

Alw fruchtfolgeflaechen neue bodenparameter 2

---

arp_npl_pub/auswertung_zonen_per_gemeinde.sql

[arp_npl_pub] Nutzungszonen aggregiert pro Gemeinde sind neu in Schema "arp_auswertung_nutzungsplanung_pub_v1"

Grunutz aggr gem

---

afu_infoflora/afu_infoflora_pub.sql
afu_infoflora/build.gradle

Bugfix https://sogis.openproject.com/projects/sogis/work_packages/1120
Änderungswunsch import und pub zusammen: https://sogis.openproject.com/projects/sogis/work_packages/1047

[afu_infoflora]Bugfix curl und pub-Job added

---

gretl_job_generator.groovy

Use `pipelineTriggers` job property instead. As described on https://github.com/jenkinsci/job-dsl-plugin/wiki/Migration#migrating-to-177

The triggers option is deprecated

---

arp_statpopent_hektarraster/build.gradle
arp_statpopent_hektarraster/hektarraster.sql
arp_statpopent_hektarraster/job.properties

Ableitung mit Aggregation von StatPop und StatEnt auf Hektarraster

[arp_statpopent_hektarraster] initial check-in

---

awjf_jagdreviere_jagdbanngebiete_pub/build.gradle

Awjf jagdreviere pub bez

---

README.md

Plus docs on how to start a GRETL job locally if it contains a publisher task referring to a file outside the job dir.

Docs: Add simiTokenService vars

---

afu_gewaesser_revitalisierung_pub/build.gradle

Gelöscht. Da ein Attribut nicht öffentlich ist.

[afu_gewaesser_revitalisierung_pub] delete Publisher Tasks

---

arp_nutzungsplanung_import/build.gradle
arp_nutzungsplanung_import/delete_arp_nutzungsplanung_transfer.sql
arp_nutzungsplanung_import/insert_arp_nutzungsplanung_transfer.sql
arp_nutzungsplanung_import_ersterfassung/build.gradle
arp_nutzungsplanung_import_ersterfassung/delete_arp_nutzungsplanung_transfer.sql
arp_nutzungsplanung_import_ersterfassung/insert_arp_nutzungsplanung_transfer.sql
arp_nutzungsplanung_pub/SO_ARP_Nutzungsplanung_Nachfuehrung_20201005.ini
arp_nutzungsplanung_pub/SO_ARP_Nutzungsplanung_Nachfuehrung_20221118.ini
arp_nutzungsplanung_pub/build.gradle
arp_nutzungsplanung_pub_easy_validation/build.gradle

neues Edit-Datenmodell mit einer neuen Zuorndungstabelle (Plan-RRB-SBV) Version für Schema (v1) bleibt

[arp_nutzungsplanung_pub,-import]

---

avt_strassenlaerm/build.gradle

Avt strassenlaerm datenabgabe 2

---

arp_nutzungsplanung_kanton_pub/Jenkinsfile
arp_nutzungsplanung_kanton_pub/SO_ARP_Nutzungsplanung_Nachfuehrung_20201005.ini
arp_nutzungsplanung_kanton_pub/SO_ARP_Nutzungsplanung_Nachfuehrung_20221118.ini
arp_nutzungsplanung_kanton_pub/build.gradle
arp_nutzungsplanung_kanton_pub/delete_arp_nutzungsplanung_export.sql
arp_nutzungsplanung_kanton_pub/insert_arp_nutzungsplanung_export_kanton_20222208.sql
arp_nutzungsplanung_kanton_pub/insert_arp_nutzungsplanung_transfer_pub.sql
arp_nutzungsplanung_pub/Jenkinsfile
arp_nutzungsplanung_pub/build.gradle
arp_nutzungsplanung_pub/delete_arp_nutzungsplanung_export.sql
arp_nutzungsplanung_pub/insert_arp_nutzungsplanung_export_20221108.sql
arp_nutzungsplanung_pub/insert_arp_nutzungsplanung_transfer_pub.sql

Publisher-Tasks bei den beiden Jobs 
- arp_nutzungsplanung_kanton_pub
- arp_nutzungsplanung_pub
Beide Jobs publizieren nun auch noch das Modell 2017 für die Geometerbüros.

Arp nutzungsplanung publisher

---

arp_nutzungsplanung_kanton_pub/Jenkinsfile
arp_nutzungsplanung_kanton_pub/Nutzungsplanung_Catalogue_CH_V1_2_20210901.xml
arp_nutzungsplanung_kanton_pub/arp_nutzungsplanung_empty.xtf
arp_nutzungsplanung_kanton_pub/arp_nutzungsplanung_mgdm.sql
arp_nutzungsplanung_kanton_pub/build.gradle
arp_nutzungsplanung_kanton_pub/config.toml
arp_nutzungsplanung_kanton_pub/truncate_all_arp_npl_mgdm_tables.sql

Arp nutzungsplanung export ai neu

---

arp_nutzungsplanung_kanton_pub/build.gradle
arp_nutzungsplanung_kanton_pub/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
arp_nutzungsplanung_kanton_pub/delete_arp_nutzungsplanung_planregister_pub_kantonal.sql
arp_nutzungsplanung_kanton_pub/insert_arp_nutzungsplanung_planregister_pub_kantonal.sql
arp_nutzungsplanung_pub/arp_nutzungsplanung_kommunal_mgdm.sql

Typo3 Export wurde wieder auskommentiert, bis die Probleme diesbezüglich gelöst sind. 
Kleiner Bugfix im kommunalen Nutzungsplan.

Arp nutzungsplanung kanton pub typo3

---

arp_mjpnl_initialisierung/Jenkinsfile
arp_mjpnl_initialisierung/build.gradle
arp_mjpnl_migration/mjpnl_dummy_entries.sql
arp_mjpnl_migration/mjpnl_leistung.sql
arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
arp_mjpnl_migration/mjpnl_postprocessing_vereinbarung_uzl-region.sql

Abhänging von einerseits https://github.com/sogis/sogis-interlis-repository/pull/59
... und andererseits https://github.com/sogis/gretljobs/pull/1441

[arp_mjpnl_initialisierung] Berücksichtigung einzelner Topics (Datasets)

---

arp_nutzungsplanung_planregister_pub_alles/Jenkinsfile
arp_nutzungsplanung_planregister_pub_alles/build.gradle

Jenkinsfile für Artefacts des xml, damit man sieht was an Typo3 geliefert wird. CURL-Befehl angepasst

[arp_nutzungsplanung_planregister_pub_alles] 

---

arp_mjpnl_migration/mjpnl_dummy_entries.sql
arp_mjpnl_migration/mjpnl_leistung.sql
arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
arp_mjpnl_migration/mjpnl_postprocessing_fill_t_basket.sql

Requires https://github.com/sogis/sogis-interlis-repository/pull/60

[arp_mjpnl_migration] Setze migriert auf TRUE

---

awjf_waldportal/build.gradle
awjf_waldportal/job.properties

Awjf waldportal publisher

---

arp_mjpnl_migration/build.gradle
arp_mjpnl_migration/mjpnl_dummy_entries.sql
arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
arp_mjpnl_migration/mjpnl_postprocessing_vereinbarungen_gemeinden_zuweisen.sql

Requires https://github.com/sogis/sogis-interlis-repository/pull/63

[arp_mjpnl_migration] Anpassungen gemäss DM Änderung

---

awjf_waldportal/job.properties

Siehe https://sogis.openproject.com/projects/task/work_packages/details/1947

[awjf_waldportal] trigger.cron deaktiviert

---

afu_gewaesserschutz_zonen_areale_pub/build.gradle
afu_gewaesserschutz_zonen_areale_pub/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
afu_gewaesserschutz_zonen_areale_pub/delete_arp_nutzungsplanung_planregister_pub_grundwasserschutz.sql
afu_gewaesserschutz_zonen_areale_pub/insert_arp_nutzungsplanung_planregister_pub_grundwasserschutz.sql
arp_naturreservate_pub/Jenkinsfile
arp_naturreservate_pub/build.gradle
arp_naturreservate_pub/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
arp_naturreservate_pub/delete_arp_nutzungsplanung_planregister_pub_naturreservate.sql
arp_naturreservate_pub/insert_arp_nutzungsplanung_planregister_pub_naturreservate.sql
awjf_statische_waldgrenze_pub/Jenkinsfile
awjf_statische_waldgrenze_pub/build.gradle
awjf_statische_waldgrenze_pub/delete_arp_nutzungsplanung_planregister_pub_doppelte_dokumente.sql
awjf_statische_waldgrenze_pub/delete_arp_nutzungsplanung_planregister_pub_statische_waldgrenze.sql
awjf_statische_waldgrenze_pub/insert_arp_nutzungsplanung_planregister_pub_waldgrenze.sql

[awjf_statische_waldgrenze_pub] Planregister upload ins Typo3 ergänzt

[arp_naturreservate_pub][afu_gewaesserschutz_zonen_areale_pub]

---

arp_nutzungsplanung_kanton_pub/insert_arp_nutzungsplanung_planregister_pub_kantonal.sql
arp_nutzungsplanung_pub/insert_arp_nutzungsplanung_planregister_pub_kommunal.sql

Tabellenname bei Sequenz korrigiert auf pub

[arp_nutzungsplanung_pub][arp_nutzungsplanung_kanton_pub] 

---

arp_mjpnl_zahlungslauf/Jenkinsfile
arp_mjpnl_zahlungslauf/build.gradle
arp_mjpnl_zahlungslauf/job.properties

Auszahlungsjahr als Parameter übergeben, damit es dann in den SQL Scripts als Bedingung verwendet werden kann.

[arp_mjpnl_zahlungslauf] Auszahlungsjahr als Parameter

---

ada_adagisa_pub/build.gradle
ada_archaeologie_pub/build.gradle
afu_klimaanalyse_pub/build.gradle
arp_mjpnl_migration/mjpnl_dummy_entries.sql
arp_mjpnl_migration/mjpnl_vereinbarung.sql

Requires https://github.com/sogis/sogis-interlis-repository/pull/74

[arp_mjpnl_migration] Berücksichtige Bewe_Id_Geprueft

---

arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschaftungseinheiten.sql
arp_mjpnl_migration/mjpnl_leistung.sql
arp_mjpnl_migration/mjpnl_postprocessing_vereinbarungen_gelan_bewirtschaftungseinheiten.sql
arp_mjpnl_migration/mjpnl_vereinbarung.sql

- Auch Leistungen von Feuchtgebieten müssen migriert werden.
- Bewe ID anhand von intersections ermitteln, da es auch mehrere überschneiden kann.
- Fix Fehler mit Waldrändern

[arp_mjpnl_migration] Rebound 9

---

avt_gvm_import/Jenkinsfile
avt_gvm_import/build.gradle
avt_gvm_import/job.properties

[avt_gvm_import] Import-Job für die Daten des Gesamtverkehrsmodell

---

arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_bewirtschafter.sql
arp_mjpnl_migration/mjpnl_postprocessing_abrechnung_per_vereinbarung.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_bewirtschafter.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_vereinbarung.sql

in die Bemerkungsfelder der Zahlungslauf Auszahlungs-Zusammenzüge.

[arp_mjpnl_zahlungslauf] Schreibe zusätzliche Info 

---

arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_hecke.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wbl_weide.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wbl_wiese.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_weide_ln.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_weide_soeg.sql
arp_mjpnl_zahlungslauf/calc_mjpnl_abrechnung_per_leistung_wiese.sql

[arp_mjpnl_zahlungslauf] Limitiere leistung_beschrieb input 

---

arp_mjpnl_zahlungslauf/build.gradle
arp_mjpnl_zahlungslauf/job.properties

wenn auszahlungsjahr nicht angegeben wird.

[arp_mjpnl_zahlungslauf] crone job und fallback aufs aktuelle Jahr 

---

afu_gefahrenkartierung_pub_export_ai/Jenkinsfile
agi_av_dm01_mopublic_pub/Jenkinsfile
agi_check_ili_export/Jenkinsfile
alw_fruchtfolgeflaechen/Jenkinsfile

Fix and improve pod definition
Fix indentation of three other Jenkinsfiles that include a pod definition

Improve alw_fruchtfolgeflaechen Jenkinsfile

---

arp_mjpnl_gelan_update/job.properties

bis das Geometrieproblem gelöst ist.

[arp_mjpnl_gelan_update] Deaktivieren des cron Jobs

---

arp_nutzungsplanung_pub/Jenkinsfile
arp_nutzungsplanung_pub/build.gradle

* Clean up task dependencies and fix tasks to execute in Jenkinsfile
* Remove Planregister files after upload
* Clean up blanks and indentation

arp_nutzungsplanung_pub: Remove Planregister files after upload

---

afu_wasserbewirtschaftung_pub/afu_wasserbewirtschaftung_trinkwasserobjekte_pub.sql

Korrektur objektbezeichnung Sammelbrunnenstube

[afu_wasserbewirtschaftung_pub] Korrektur objektbezeichnung

---

afu_wasserbewirtschaftung_pub/build.gradle
afu_wasserbewirtschaftung_pub/delete_oberflaechenhydrometrie.sql

Anpassung gretl-job zur Loeschung nicht mehr benoetigter Daten

[afu_wasserbewirtschaftung_pub] Anpassung gretl-job

---

agi_lk_nachfuehrungseinheiten_pub/build.gradle
agi_lk_nachfuehrungseinheiten_pub/select_transfer_data.sql

[agi_lk_nachfuehrungseinheiten_pub] Data conversion and publisher job

---

amb_zivilschutz_adressen_export/build.gradle

https://sogis.openproject.com/projects/gretl/work_packages/1381

[amb_zivilschutz_adressen_export] Upload CSV file in production environment only

---

arp_mjpnl_gelan_update/build.gradle
arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschafter.sql
arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_bewirtschaftungseinheiten.sql
arp_mjpnl_gelan_update/mjpnl_update_vereinbarungen_gelan_kulturflaechen.sql

wenn bewirtschafter (pid_gelan) ändert und nicht wenn bewe_id ändert.

[arp_mjpnl_gelan_update] setzen von bewe_id_geprueft auf false

---

alw_landwirtschaft_tierhaltung_import_bodenbedeckung/job.properties
alw_landwirtschaft_tierhaltung_import_massnahmen/job.properties
alw_landwirtschaft_tierhaltung_pub/job.properties

[alw_landwirtschaft_tierhaltung]

---

agi_ausgleichsabgabe_pub/agi_ausgleichsabgabe_pub.sql
agi_ausgleichsabgabe_pub/build.gradle
agi_ausgleichsabgabe_pub/job.properties

- Neuer gretljob für das pub-Schema

[agi_ausgleichsabgabe] new pub-gretljob

---

arp_nutzungsplanung_pub/build.gradle

https://sogis.openproject.com/projects/task/work_packages/2439

[arp_nutzungsplanung_pub] delete UserFormats = true

---

agi_adressen_pub/agi_adressen_pub_verbindungslinie_strasse_hausnummer.sql

https://sogis.openproject.com/projects/task/work_packages/2466

[agi_adressen_pub] add WHERE Bedingung

---

dsbjd_ausgleichsabgabe_pub/build.gradle
dsbjd_ausgleichsabgabe_pub/dsbjd_ausgleichsabgabe_pub.sql
dsbjd_ausgleichsabgabe_pub/job.properties

Neuer Pub-Job für das Publikations-Schema der Ausgleichsabgaben

[dsbjd_ausgleichsabgabe] new pub gretl-job

---

arp_mjpnl_v2_auswertung/build.gradle
arp_mjpnl_v2_auswertung/calc_jahresbericht_abgeltungen.sql
arp_mjpnl_v2_auswertung/calc_mjpnl_abrechnung_per_vereinbarung.sql
arp_mjpnl_v2_auswertung/cleanup_jahresbericht_abgeltungen.sql
arp_mjpnl_v2_auswertung/cleanup_rrb_bewirtschafterwechsel.sql
arp_mjpnl_v2_auswertung/cleanup_rrb_neue_vereinbarung.sql
arp_mjpnl_v2_auswertung/cleanup_snapshot_wbl_weide.sql
arp_mjpnl_v2_auswertung/cleanup_snapshot_wbl_wiese.sql
arp_mjpnl_v2_auswertung/cleanup_snapshot_weide.sql
arp_mjpnl_v2_auswertung/cleanup_snapshot_wiese.sql
arp_mjpnl_v2_auswertung/job.properties

[arp_mjpnl_v2_auswertung] Kalkulieren und abfüllen der Tabellen

---

alw_drainagen_pub/vsadssmini_saa_schacht_dr.sql

[alw_drainagen_pub] update sql for Knoten

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql
afu_bodendaten_nabodat_abfrage_pub/build.gradle
afu_bodendaten_nabodat_abfrage_pub/job.properties

Neuer GRETL-Job für die Nabodat Bodenprofilabfrage.
- Noch nicht vollständig (Testphase)

[afu_nabodat] new gretl-job

---

afu_asiatische_hornisse_pub/job.properties

[afu_asiatische_hornisse] job properties added

---

afu_asiatische_hornisse_pub/job.properties

logRotator.numToKeep=30
triggers.cron=H H(1-3) * * *

[afu_asiatische_hornisse_pub] delete

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql

Anpassung des zusammengesetzten Attributs ausgangsmaterial_alle

[afu_nabodat] Anpassung Gretl-Job

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql
afu_bodendaten_nabodat_abfrage_pub/build.gradle
afu_bodendaten_nabodat_abfrage_pub/profilblatt.sql

sql um das Attribut "profilblatt" zu aktualisieren

[afu_nabodat] update profilblatt

---

README.md

Linked to https://github.com/sogis/schema-jobs/pull/402

Docs on importDevelopmentData task

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql
afu_bodendaten_nabodat_abfrage_pub/build.gradle
afu_bodendaten_nabodat_abfrage_pub/horizontdaten.sql

Einige kosmetische Korrekturen der sql.

[afu_nabodat] kosmetische Korrekturen

---

dsbjd_ausgleichsabgabe_pub/dsbjd_ausgleichsabgabe_pub.sql

Anpassung wie Dokumente übertragen werden

[dsbjd_ausgleichsabgabe] Anpassung GRETL-Job

---

afu_bodendaten_nabodat_abfrage_pub/update_horizont.sql

Im update-sql fehlten zwei Attribute

[afu_nabodat] kleine Anpassung sql

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql
afu_bodendaten_nabodat_abfrage_pub/build.gradle
afu_bodendaten_nabodat_abfrage_pub/profilblatt.sql
afu_bodendaten_nabodat_abfrage_pub/update_horizont.sql

Im Schemajob wurde "name by topic" auf false gesetzt. Dementsprechend müssen einige sql angepasst werden.

[afu_nabodat] Anpassung sql auf Schemajob

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql
afu_bodendaten_nabodat_abfrage_pub/build.gradle
afu_bodendaten_nabodat_abfrage_pub/job.properties
afu_bodendaten_nabodat_abfrage_pub/profilblatt.sql
afu_bodendaten_nabodat_abfrage_pub/update_horizont.sql

im sql profilblatt sollen je nach host (Integration, Produktion) unterschiedliche hostnamen verwendet werden.

[afu_nabodat] Anpassungen GRETL-Job

---

arp_mjpnl_v2_zahlungslauf/auswertung_calc_jahresbericht_abgeltungen.sql
arp_mjpnl_v2_zahlungslauf/calc_mjpnl_abrechnung_per_bewirtschafter.sql

in Abrechnung_per_Bewirtschafter

[arp_mjpnl_v2_zahlungslauf] Kreditornummer 

---

afu_bodendaten_nabodat_abfrage_pub/bodenprofil.sql
afu_bodendaten_nabodat_abfrage_pub/build.gradle
afu_bodendaten_nabodat_abfrage_pub/job.properties
afu_bodendaten_nabodat_abfrage_pub/profilblatt.sql
afu_bodendaten_nabodat_abfrage_pub/update_horizont.sql

Je nach Umgebung wird ein anderer Hostname verwendet

[afu_nabodat] add sqlParameter

---

docker-compose.yml

Due to https://github.com/sogis/openshift-templates/pull/134

Update GRETL tag to 2.2.617

---

README.md
hba_gebaeude_pub_v2/job.properties
hba_grundstuecke_pub_v2/job.properties

HBA permissions

---

awjf_rodung_rodungsersatz_mgdm/build.gradle
awjf_rodung_rodungsersatz_mgdm/ersatzmassnahmennl.sql
awjf_rodung_rodungsersatz_mgdm/ersatzverzicht.sql
awjf_rodung_rodungsersatz_mgdm/job.properties
awjf_rodung_rodungsersatz_mgdm/massnahmenltyp.sql
awjf_rodung_rodungsersatz_mgdm/objekt.sql
awjf_rodung_rodungsersatz_mgdm/rodungsbewilligung.sql
awjf_rodung_rodungsersatz_pub/awjf_rodung_rodungsersatz_flaeche.sql
awjf_rodung_rodungsersatz_pub/awjf_rodung_rodungsersatz_punkt.sql
awjf_rodung_rodungsersatz_pub/build.gradle
awjf_rodung_rodungsersatz_pub/job.properties

Erste Versionen der neuen Gretljobs.

[awjf_rodung_rodungsersatz] Neue Gretljobs

---

arp_richtplan_gewaesserschutz_pub/arp_richtplan_pub_gewaesserschutz.sql
arp_richtplan_richtplan_pub/build.gradle

Polygone wurden mit st_union teilweise nicht schön aufgelöst, daher habe ich einen Buffer eingefügt.

[arp_richtplan] Anpassung Gretljob

---

awjf_rodung_rodungsersatz_pub/awjf_rodung_rodungsersatz_flaeche.sql

Select auf Attribut ersatzverzicht_txt wurde angepasst.

[awjf_rodung_rodungsersatz] Anpassung sql

---

awjf_rodung_rodungsersatz_pub/awjf_rodung_rodungsersatz_flaeche.sql

Anpassung wie das Attribut ErsatzVerzicht in das Pub-Schema übertragen wird.

[awjf_rodung_rodungsersatz] Kleine Anpassungen SQL

---

awjf_rodung_rodungsersatz_mgdm/ersatzmassnahmennl.sql
awjf_rodung_rodungsersatz_mgdm/ersatzverzicht.sql
awjf_rodung_rodungsersatz_mgdm/massnahmenltyp.sql
awjf_rodung_rodungsersatz_mgdm/objekt.sql
awjf_rodung_rodungsersatz_mgdm/rodungsbewilligung.sql
awjf_rodung_rodungsersatz_pub/awjf_rodung_rodungsersatz_flaeche.sql
awjf_rodung_rodungsersatz_pub/build.gradle

[awjf_rodung_rodungsersatz] Anpassung MGDM-Job

---

arp_mjpnl_auszahlung/job.properties
arp_mjpnl_gelan_update/job.properties
arp_mjpnl_zahlungslauf/job.properties

Deactivate cron jobs on old arp_mjpnl_v1

[arp_mjpnl_*] Deactivate cron jobs

---

arp_arbeitszonenbewirtschaftung_inventar_pub/select_staging.sql

[arp_arbeitszonenbewirtschaftung_inventar_pub] Nutzungsgrad angepasst

---

arp_mjpnl_v2_zahlungslauf/auswertung_calc_rrb_neue_vereinbarung.sql

Jahr des Startdatums == aktuelles Jahr, anstelle von rrp_publiziert Datum

[arp_mjpnl_v2] Fülle Tabelle anhand von startdatum

---

arp_mjpnl_v2_zahlungslauf/auswertung_calc_jahresbericht_abgeltungen.sql

anhand von JSON string in Bemerkung `***{"meter":230,"grenze":true}***`

[arp_mjpnl_v2] Laufmeterkalkulation

---

agi_av_gwr_abgleich_pub/build.gradle
agi_check_ili_export/build.gradle
alw_landwirtschaft_tierhaltung_import_bodenbedeckung/build.gradle
alw_landwirtschaft_tierhaltung_import_massnahmen/build.gradle
alw_landwirtschaft_tierhaltung_pub/build.gradle
arp_mjpnl_gelan_update/build.gradle
arp_mjpnl_initialisierung/build.gradle
arp_mjpnl_v2_gelan_update/build.gradle
arp_mjpnl_v2_initialisierung/build.gradle
avt_kantonsstrassen_pub/build.gradle
awjf_waldpflege_kontrolle_pub/build.gradle
awjf_waldportal/build.gradle

Required for GRETL 3.
Found those by doing `grep -r -E dataFile.*Paths`

Provide dataFile as java.io.File

---

arp_sein_konfiguration_local/attach_editdb.sql
arp_sein_konfiguration_local/attach_pubdb.sql
arp_sein_konfiguration_local/build.gradle
arp_sein_konfiguration_local/bundesinventar_amphibien_laichgebiete_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_amphibien_wanderobjekte_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_auen_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_bln_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_flachmmore_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_hochmoore_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_trockenwiesen_trockenweiden_import_shp.sql
arp_sein_konfiguration_local/bundesinventar_vogelreservate_import_shp.sql
arp_sein_konfiguration_local/clean_tables.sql
arp_sein_konfiguration_local/create_table_duckdb.sql
arp_sein_konfiguration_local/datenaggregation.sql
arp_sein_konfiguration_local/detach_db.sql
arp_sein_konfiguration_local/job.properties
arp_sein_konfiguration_local/load_extensions.sql
arp_sein_konfiguration_local/objektinfos_grundlagen_import_postgis.sql
arp_sein_konfiguration_local/postgis_agglo_massnahmen_gen1_import.sql
arp_sein_konfiguration_local/postgis_agglo_massnahmen_gen2_import.sql
arp_sein_konfiguration_local/postgis_agglo_massnahmen_gen3_import.sql
arp_sein_konfiguration_local/postgis_agglo_massnahmen_gen4_import.sql
arp_sein_konfiguration_local/transfer_grundlagen.sql
arp_sein_konfiguration_local/update_thema_gruppe.sql

Der GRETL-Job enthält noch nicht alle Daten. Zurzeit kann dieser auch nur lokal ausgeführt werden.

[arp_sein] Erste Version GRETL-Job (noch nicht vollständig)

---

README.md
amb_zivilschutz_adressen_export/build.gradle

And rename _ftpServerZivilschutz_ variables.
* https://sogis.openproject.com/work_packages/2918
* https://sogis.openproject.com/work_packages/1455

Add sftpServerSEinApp variables

---

afu_neophyten_pub/build.gradle

GRETL 3.1 introduces some API breaks: https://sogis.openproject.com/projects/task/work_packages/2853

[afu_neophyten_pub] Fixes for GRETL 3.1

---

README.md
agi_av_meldewesen/build.gradle
arp_sein_upload_test/build.gradle

* Update path to SSH key
* Describe how to mount a key when running job locally

Update path to key

---

alw_landwirtschaft_tierhaltung_pub/build.gradle

https://sogis.openproject.com/projects/sogis/work_packages/3013

[alw_landwirtschaft_tierhaltung_pub] Changed Jahr to 2026

---

ada_archaeologie_pub/build.gradle
afu_abbaustellen_pub/build.gradle
afu_altlasten_import_pub/build.gradle
afu_bodenprofilstandorte_nabodat_pub/build.gradle
afu_geotope_pub/build.gradle
afu_gewaesser_gewaessereigenschaften_pub/build.gradle
afu_igel/build.gradle
afu_naturereigniskataster_mgdm_import/build.gradle
afu_wasserbewirtschaftung_pub/build.gradle
agi_av_dm01_mopublic_pub/0_dm01_so/build.gradle
agi_av_dm01_mopublic_pub/2_mopublic/build.gradle
agi_gb2av_controlling/build.gradle
agi_hoheitsgrenzen_pub/build.gradle
agi_mopublic_pub/build.gradle
alw_landwirtschaft_tierhaltung_pub/build.gradle
arp_naturreservate_pub/build.gradle
avt_kantonsstrassen_pub/build.gradle
avt_oeffentlicher_verkehr_pub/build.gradle
avt_verkehrszaehlstellen_pub/build.gradle
awjf_gewaesser_fischerei_pub/build.gradle
awjf_schutzwald_pub/build.gradle
awjf_wald_pub/build.gradle
awjf_waldplan_bestandeskarte_pub/build.gradle
awjf_waldwanderwege_pub/build.gradle
gesa_leistungserbringerstandorte_analyse_pub/build.gradle

Rückbau der Solr-Abhängigkeiten

[Search service] removed refreshSolr tasks
